package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmReceivablesPlanProduct<M extends BaseCrmReceivablesPlanProduct<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setPlanProductId(String planProductId) {
		set("plan_product_id", planProductId);
		return (M)this;
	}

	public String getPlanProductId() {
		return getStr("plan_product_id");
	}

	public M setPlanId(Integer planId) {
		set("plan_id", planId);
		return (M)this;
	}

	public Integer getPlanId() {
		return getInt("plan_id");
	}

	public M setProductId(Integer productId) {
		set("product_id", productId);
		return (M)this;
	}

	public Integer getProductId() {
		return getInt("product_id");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public Integer getIsDelete() {
		return getInt("is_delete");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setMark(String mark) {
		set("mark", mark);
		return (M)this;
	}

	public String getMark() {
		return getStr("mark");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
