package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * @author system
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmReceivablesAbnormalFunds<M extends BaseCrmReceivablesAbnormalFunds<M>> extends CrmModel<M> implements IBean {

	/**
	 * ID
	 */
	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * ID
	 */
	public Long getId() {
		return getLong("id");
	}

	/**
	 * 支付号
	 */
	public M setPaymentNo(String paymentNo) {
		set("payment_no", paymentNo);
		return (M)this;
	}
	
	/**
	 * 支付号
	 */
	public String getPaymentNo() {
		return getStr("payment_no");
	}

	/**
	 * OA人工干预申请单号
	 */
	public M setOaNo(String oaNo) {
		set("oa_no", oaNo);
		return (M)this;
	}
	
	/**
	 * OA人工干预申请单号
	 */
	public String getOaNo() {
		return getStr("oa_no");
	}

	/**
	 * 异常资金状态 0 未处理 1 处理中 2 处理完成
	 */
	public M setFundsState(Integer fundsState) {
		set("funds_state", fundsState);
		return (M)this;
	}
	
	/**
	 * 异常资金状态 0 未处理 1 处理中 2 处理完成
	 */
	public Integer getFundsState() {
		return getInt("funds_state");
	}

	/**
	 * 回款计划号
	 */
	public M setBizNo(String bizNo) {
		set("biz_no", bizNo);
		return (M)this;
	}
	
	/**
	 * 回款计划号
	 */
	public String getBizNo() {
		return getStr("biz_no");
	}

	/**
	 * 业务类型
	 */
	public M setBizType(String bizType) {
		set("biz_type", bizType);
		return (M)this;
	}
	
	/**
	 * 业务类型
	 */
	public String getBizType() {
		return getStr("biz_type");
	}

	/**
	 * 0: 未删除 1:已删除
	 */
	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	/**
	 * 0: 未删除 1:已删除
	 */
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 记录创建时间
	 */
	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	/**
	 * 记录创建时间
	 */
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	/**
	 * 记录更新时间
	 */
	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	/**
	 * 记录更新时间
	 */
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	/**
	 * 环境标
	 */
	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	/**
	 * 环境标
	 */
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	/**
	 * 备注
	 */
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

}
