package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmCustomer<M extends BaseCrmCustomer<M>> extends CrmModel<M> implements IBean {

	public M setCustomerId(Long customerId) {
		set("customer_id", customerId);
		return (M)this;
	}
	
	public Long getCustomerId() {
		return getLong("customer_id");
	}

	public M setCustomerName(String customerName) {
		set("customer_name", customerName);
		return (M)this;
	}
	
	public String getCustomerName() {
		return getStr("customer_name");
	}

	public M setIsLock(Integer isLock) {
		set("is_lock", isLock);
		return (M)this;
	}
	
	public Integer getIsLock() {
		return getInt("is_lock");
	}

	public M setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
		return (M)this;
	}
	
	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public M setDealStatus(String dealStatus) {
		set("deal_status", dealStatus);
		return (M)this;
	}
	
	public String getDealStatus() {
		return getStr("deal_status");
	}

	public M setTelephone(String telephone) {
		set("telephone", telephone);
		return (M)this;
	}
	
	public String getTelephone() {
		return getStr("telephone");
	}

	public M setWebsite(String website) {
		set("website", website);
		return (M)this;
	}
	
	public String getWebsite() {
		return getStr("website");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}
	
	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
		return (M)this;
	}
	
	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public M setOwnerTime(java.util.Date ownerTime) {
		set("owner_time", ownerTime);
		return (M)this;
	}
	
	public java.util.Date getOwnerTime() {
		return get("owner_time");
	}

	public M setRoUserId(String roUserId) {
		set("ro_user_id", roUserId);
		return (M)this;
	}
	
	public String getRoUserId() {
		return getStr("ro_user_id");
	}

	public M setRwUserId(String rwUserId) {
		set("rw_user_id", rwUserId);
		return (M)this;
	}
	
	public String getRwUserId() {
		return getStr("rw_user_id");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}
	
	public String getAddress() {
		return getStr("address");
	}

	public M setLocation(String location) {
		set("location", location);
		return (M)this;
	}
	
	public String getLocation() {
		return getStr("location");
	}

	public M setDetailAddress(String detailAddress) {
		set("detail_address", detailAddress);
		return (M)this;
	}
	
	public String getDetailAddress() {
		return getStr("detail_address");
	}

	public M setLng(String lng) {
		set("lng", lng);
		return (M)this;
	}
	
	public String getLng() {
		return getStr("lng");
	}

	public M setLat(String lat) {
		set("lat", lat);
		return (M)this;
	}
	
	public String getLat() {
		return getStr("lat");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}
	
	public String getBatchId() {
		return getStr("batch_id");
	}

	public M setLeadsId(Long leadsId) {
		set("leads_id", leadsId);
		return (M)this;
	}
	
	public Long getLeadsId() {
		return getLong("leads_id");
	}

	public M setCustomerNo(String customerNo) {
		set("customer_no", customerNo);
		return (M)this;
	}
	
	public String getCustomerNo() {
		return getStr("customer_no");
	}

	public M setDistributor(String distributor) {
		set("distributor", distributor);
		return (M)this;
	}
	
	public String getDistributor() {
		return getStr("distributor");
	}

	public M setCustomerGrade(String customerGrade) {
		set("customer_grade", customerGrade);
		return (M)this;
	}
	
	public String getCustomerGrade() {
		return getStr("customer_grade");
	}

	public M setCustomerType(String customerType) {
		set("customer_type", customerType);
		return (M)this;
	}
	
	public String getCustomerType() {
		return getStr("customer_type");
	}

	public M setRegisterCapital(String registerCapital) {
		set("register_capital", registerCapital);
		return (M)this;
	}
	
	public String getRegisterCapital() {
		return getStr("register_capital");
	}

	public M setLegalPerson(String legalPerson) {
		set("legal_person", legalPerson);
		return (M)this;
	}
	
	public String getLegalPerson() {
		return getStr("legal_person");
	}

	public M setRegistrationNumber(String registrationNumber) {
		set("registration_number", registrationNumber);
		return (M)this;
	}
	
	public String getRegistrationNumber() {
		return getStr("registration_number");
	}

	public M setCreditCode(String creditCode) {
		set("credit_code", creditCode);
		return (M)this;
	}
	
	public String getCreditCode() {
		return getStr("credit_code");
	}

	public M setIsMultiple(Integer isMultiple) {
		set("is_multiple", isMultiple);
		return (M)this;
	}
	
	public Integer getIsMultiple() {
		return getInt("is_multiple");
	}

	public M setDeptId(Integer deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public Integer getDeptId() {
		return getInt("dept_id");
	}

	public M setCustomerOrigin(String customerOrigin) {
		set("customer_origin", customerOrigin);
		return (M)this;
	}
	
	public String getCustomerOrigin() {
		return getStr("customer_origin");
	}

	public M setIsAttestation(String isAttestation) {
		set("is_attestation", isAttestation);
		return (M)this;
	}
	
	public String getIsAttestation() {
		return getStr("is_attestation");
	}

	public M setIdCard(String idCard) {
		set("id_card", idCard);
		return (M)this;
	}
	
	public String getIdCard() {
		return getStr("id_card");
	}

	public M setIdCardUrl(String idCardUrl) {
		set("id_card_url", idCardUrl);
		return (M)this;
	}
	
	public String getIdCardUrl() {
		return getStr("id_card_url");
	}

	public M setRegistrationImgUrl(String registrationImgUrl) {
		set("registration_img_url", registrationImgUrl);
		return (M)this;
	}
	
	public String getRegistrationImgUrl() {
		return getStr("registration_img_url");
	}

	public M setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}
	
	public Integer getIsDelete() {
		return getInt("is_delete");
	}

	public M setOrganizationImgUrl(String organizationImgUrl) {
		set("organization_img_url", organizationImgUrl);
		return (M)this;
	}
	
	public String getOrganizationImgUrl() {
		return getStr("organization_img_url");
	}

	public M setFollowup(Integer followup) {
		set("followup", followup);
		return (M)this;
	}
	
	public Integer getFollowup() {
		return getInt("followup");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public M setPartner(String partner) {
		set("partner", partner);
		return (M)this;
	}
	
	public String getPartner() {
		return getStr("partner");
	}

	public M setRegistrationDate(java.util.Date registrationDate) {
		set("registration_date", registrationDate);
		return (M)this;
	}
	
	public java.util.Date getRegistrationDate() {
		return get("registration_date");
	}

	public M setRepeatMark(Integer repeatMark) {
		set("repeat_mark", repeatMark);
		return (M)this;
	}
	
	public Integer getRepeatMark() {
		return getInt("repeat_mark");
	}

	public M setIndustryCode(String industryCode) {
		set("industry_code", industryCode);
		return (M)this;
	}
	
	public String getIndustryCode() {
		return getStr("industry_code");
	}

	public M setFromSource(Integer fromSource) {
		set("from_source", fromSource);
		return (M)this;
	}
	
	public Integer getFromSource() {
		return getInt("from_source");
	}

}
