package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmContacts<M extends BaseCrmContacts<M>> extends CrmModel<M> implements IBean {

	public M setContactsId(Long contactsId) {
		set("contacts_id", contactsId);
		return (M)this;
	}

	public Long getContactsId() {
		return getLong("contacts_id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
		return (M)this;
	}

	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public String getMobile() {
		return getStr("mobile");
	}

	public M setTelephone(String telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public String getTelephone() {
		return getStr("telephone");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}

	public String getEmail() {
		return getStr("email");
	}

	public M setPost(String post) {
		set("post", post);
		return (M)this;
	}

	public String getPost() {
		return getStr("post");
	}

	public M setCustomerId(Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public M setAddress(String address) {
		set("address", address);
		return (M)this;
	}

	public String getAddress() {
		return getStr("address");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
		return (M)this;
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

	//add by chaokun.ding
	//微信
	public M setWeChat(String wechat) {
		set("wechat", wechat);
		return (M)this;
	}

	public String getWeChat() {
		return getStr("wechat");
	}

	//角色
	public M setRole(String role) {
		set("role", role);
		return (M)this;
	}

	public String getRole() {
		return getStr("role");
	}

	//态度
	public M setAttitude(String attitude) {
		set("attitude", attitude);
		return (M)this;
	}

	public String getAttitude() {
		return getStr("attitude");
	}

	//爱好
	public M setHobby(String hobby) {
		set("hobby", hobby);
		return (M)this;
	}

	public String getHobby() {
		return getStr("hobby");
	}

}
