package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSensitiveEntity<M extends BaseSensitiveEntity<M>> extends CrmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}

	public java.lang.String getName() {
		return getStr("name");
	}

	public M setEntryName(java.lang.String entryName) {
		set("entry_name", entryName);
		return (M)this;
	}

	public java.lang.String getEntryName() {
		return getStr("entry_name");
	}

	public M setFieldName(java.lang.String fieldName) {
		set("field_name", fieldName);
		return (M)this;
	}

	public java.lang.String getFieldName() {
		return getStr("field_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(java.lang.String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public java.lang.String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setMark(java.lang.String mark) {
		set("mark", mark);
		return (M)this;
	}

	public java.lang.String getMark() {
		return getStr("mark");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}

}
