package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

import java.util.Date;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmCallRecord<M extends BaseCrmCallRecord<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setName(java.lang.String name) {
		set("name", name);
		return (M)this;
	}
	
	public java.lang.String getName() {
		return getStr("name");
	}

	public M setTypes(java.lang.String types) {
		set("types", types);
		return (M)this;
	}
	
	public java.lang.String getTypes() {
		return getStr("types");
	}

	public M setTypesId(java.lang.Integer typesId) {
		set("types_id", typesId);
		return (M)this;
	}
	
	public java.lang.Integer getTypesId() {
		return getInt("types_id");
	}

	public M setCallingUserId(java.lang.Long callingUserId) {
		set("calling_user_id", callingUserId);
		return (M)this;
	}
	
	public java.lang.Long getCallingUserId() {
		return getLong("calling_user_id");
	}

	public M setCallingName(java.lang.String callingName) {
		set("calling_name", callingName);
		return (M)this;
	}
	
	public java.lang.String getCallingName() {
		return getStr("calling_name");
	}

	public M setCalledName(java.lang.String calledName) {
		set("called_name", calledName);
		return (M)this;
	}
	
	public java.lang.String getCalledName() {
		return getStr("called_name");
	}

	public M setCalledNumber(java.lang.String calledNumber) {
		set("called_number", calledNumber);
		return (M)this;
	}
	
	public java.lang.String getCalledNumber() {
		return getStr("called_number");
	}

	public M setCallStartTime(java.util.Date callStartTime) {
		set("call_start_time", callStartTime);
		return (M)this;
	}
	
	public java.util.Date getCallStartTime() {
		return get("call_start_time");
	}

	public M setCallDuration(java.lang.Integer callDuration) {
		set("call_duration", callDuration);
		return (M)this;
	}
	
	public java.lang.Integer getCallDuration() {
		return getInt("call_duration");
	}

	public M setContactId(java.lang.String contactId) {
		set("contact_id", contactId);
		return (M)this;
	}
	
	public java.lang.String getContactId() {
		return getStr("contact_id");
	}

	public M setFileName(java.lang.String fileName) {
		set("file_name", fileName);
		return (M)this;
	}
	
	public java.lang.String getFileName() {
		return getStr("file_name");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(java.lang.String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public java.lang.String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCallType(java.lang.String callType) {
		set("call_type", callType);
		return (M)this;
	}
	
	public java.lang.String getCallType() {
		return getStr("call_type");
	}

	public M setConnectStates(java.lang.String connectStates) {
		set("connect_states", connectStates);
		return (M)this;
	}
	
	public java.lang.String getConnectStates() {
		return getStr("connect_states");
	}

	public M setOutboundCallStartTime(Date outboundCallStartTime) {
		set("outbound_call_start_time", outboundCallStartTime);
		return (M)this;
	}
	
	public java.lang.String getOutboundCallStartTime() {
		return getStr("outbound_call_start_time");
	}

}
