package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmLeads<M extends BaseCrmLeads<M>> extends CrmModel<M> implements IBean {

	public M setLeadsId(java.lang.Long leadsId) {
		set("leads_id", leadsId);
		return (M)this;
	}

	public java.lang.Long getLeadsId() {
		return getLong("leads_id");
	}

	public M setFollowup(java.lang.Integer followup) {
		set("followup", followup);
		return (M)this;
	}

	public java.lang.Integer getFollowup() {
		return getInt("followup");
	}

	public M setIsTransform(java.lang.Integer isTransform) {
		set("is_transform", isTransform);
		return (M)this;
	}

	public java.lang.Integer getIsTransform() {
		return getInt("is_transform");
	}

	public M setLeadsName(java.lang.String leadsName) {
		set("leads_name", leadsName);
		return (M)this;
	}

	public java.lang.String getLeadsName() {
		return getStr("leads_name");
	}

	public M setCustomerId(java.lang.Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}

	public java.lang.Integer getCustomerId() {
		return getInt("customer_id");
	}

	public M setNextTime(java.util.Date nextTime) {
		set("next_time", nextTime);
		return (M)this;
	}

	public java.util.Date getNextTime() {
		return get("next_time");
	}

	public M setTelephone(java.lang.String telephone) {
		set("telephone", telephone);
		return (M)this;
	}

	public java.lang.String getTelephone() {
		return getStr("telephone");
	}

	public M setMobile(java.lang.String mobile) {
		set("mobile", mobile);
		return (M)this;
	}

	public java.lang.String getMobile() {
		return getStr("mobile");
	}

	public M setAddress(java.lang.String address) {
		set("address", address);
		return (M)this;
	}

	public java.lang.String getAddress() {
		return getStr("address");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}

	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setCreateUserId(java.lang.Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public java.lang.Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setOwnerUserId(java.lang.Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
		return (M)this;
	}

	public java.lang.Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setBatchId(java.lang.String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}

	public java.lang.String getBatchId() {
		return getStr("batch_id");
	}

	public M setDeptId(java.lang.String deptId) {
		set("dept_id", deptId);
		return (M)this;
	}

	public java.lang.String getDeptId() {
		return getStr("dept_id");
	}

	public M setLeadsNo(java.lang.String leadsNo) {
		set("leads_no", leadsNo);
		return (M)this;
	}

	public java.lang.String getLeadsNo() {
		return getStr("leads_no");
	}

	public M setLeadsExpatiation(java.lang.String leadsExpatiation) {
		set("leads_expatiation", leadsExpatiation);
		return (M)this;
	}

	public java.lang.String getLeadsExpatiation() {
		return getStr("leads_expatiation");
	}

	public M setLeadCome(java.lang.Integer leadCome) {
		set("lead_come", leadCome);
		return (M)this;
	}

	public java.lang.Integer getLeadCome() {
		return getInt("lead_come");
	}

	public M setCustomerIndustry(java.lang.String customerIndustry) {
		set("customer_industry", customerIndustry);
		return (M)this;
	}

	public java.lang.String getCustomerIndustry() {
		return getStr("customer_industry");
	}

	public M setCustomerLevel(java.lang.String customerLevel) {
		set("customer_level", customerLevel);
		return (M)this;
	}

	public java.lang.String getCustomerLevel() {
		return getStr("customer_level");
	}

	public M setContactUser(java.lang.String contactUser) {
		set("contact_user", contactUser);
		return (M)this;
	}

	public java.lang.String getContactUser() {
		return getStr("contact_user");
	}

	public M setCompany(java.lang.String company) {
		set("company", company);
		return (M)this;
	}

	public java.lang.String getCompany() {
		return getStr("company");
	}

	public M setContactDeptName(java.lang.String contactDeptName) {
		set("contact_dept_name", contactDeptName);
		return (M)this;
	}

	public java.lang.String getContactDeptName() {
		return getStr("contact_dept_name");
	}

	public M setPosition(java.lang.String position) {
		set("position", position);
		return (M)this;
	}

	public java.lang.String getPosition() {
		return getStr("position");
	}

	public M setEmail(java.lang.String email) {
		set("email", email);
		return (M)this;
	}

	public java.lang.String getEmail() {
		return getStr("email");
	}

	public M setWeChat(java.lang.String weChat) {
		set("we_chat", weChat);
		return (M)this;
	}

	public java.lang.String getWeChat() {
		return getStr("we_chat");
	}

	public M setRequireDescription(java.lang.String requireDescription) {
		set("require_description", requireDescription);
		return (M)this;
	}

	public java.lang.String getRequireDescription() {
		return getStr("require_description");
	}

	public M setDetailAddress(java.lang.String detailAddress) {
		set("detail_address", detailAddress);
		return (M)this;
	}

	public java.lang.String getDetailAddress() {
		return getStr("detail_address");
	}

	public M setAccuracyRequirements(java.lang.String accuracyRequirements) {
		set("accuracy_requirements", accuracyRequirements);
		return (M)this;
	}

	public java.lang.String getAccuracyRequirements() {
		return getStr("accuracy_requirements");
	}

	public M setCustomerQuality(java.lang.String customerQuality) {
		set("customer_quality", customerQuality);
		return (M)this;
	}

	public java.lang.String getCustomerQuality() {
		return getStr("customer_quality");
	}

	public M setReceiveTime(java.util.Date receiveTime) {
		set("receive_time", receiveTime);
		return (M)this;
	}

	public java.util.Date getReceiveTime() {
		return get("receive_time");
	}

	public M setSendEmailTimes(Integer sendEmailTimes) {
		set("send_email_times", sendEmailTimes);
		return (M)this;
	}

	public Integer getSendEmailTimes() {
		return getInt("send_email_times");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
