package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmChangeLog<M extends BaseCrmChangeLog<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setRequestId(String requestId) {
		set("request_id", requestId);
		return (M)this;
	}
	
	public String getRequestId() {
		return getStr("request_id");
	}

	public M setFromChannel(Integer fromChannel) {
		set("from_channel", fromChannel);
		return (M)this;
	}
	
	public Integer getFromChannel() {
		return getInt("from_channel");
	}

	public M setFromChannelEvent(String fromChannelEvent) {
		set("from_channel_event", fromChannelEvent);
		return (M)this;
	}
	
	public String getFromChannelEvent() {
		return getStr("from_channel_event");
	}

	public M setFromId(String fromId) {
		set("from_id", fromId);
		return (M)this;
	}
	
	public String getFromId() {
		return getStr("from_id");
	}

	public M setChangeHistory(String changeHistory) {
		set("change_history", changeHistory);
		return (M)this;
	}
	
	public String getChangeHistory() {
		return getStr("change_history");
	}

	public M setOldOwnerUserId(Long oldOwnerUserId) {
		set("old_owner_user_id", oldOwnerUserId);
		return (M)this;
	}
	
	public Long getOldOwnerUserId() {
		return getLong("old_owner_user_id");
	}

	public M setOldOwnerUserDeptId(Long oldOwnerUserDeptId) {
		set("old_owner_user_dept_id", oldOwnerUserDeptId);
		return (M)this;
	}
	
	public Long getOldOwnerUserDeptId() {
		return getLong("old_owner_user_dept_id");
	}

	public M setOldOwnerUserDeptIdTree(String oldOwnerUserDeptIdTree) {
		set("old_owner_user_dept_id_tree", oldOwnerUserDeptIdTree);
		return (M)this;
	}
	
	public String getOldOwnerUserDeptIdTree() {
		return getStr("old_owner_user_dept_id_tree");
	}

	public M setOldOwnerUserDeptNameTree(String oldOwnerUserDeptNameTree) {
		set("old_owner_user_dept_name_tree", oldOwnerUserDeptNameTree);
		return (M)this;
	}
	
	public String getOldOwnerUserDeptNameTree() {
		return getStr("old_owner_user_dept_name_tree");
	}

	public M setNewOwnerUserId(Long newOwnerUserId) {
		set("new_owner_user_id", newOwnerUserId);
		return (M)this;
	}
	
	public Long getNewOwnerUserId() {
		return getLong("new_owner_user_id");
	}

	public M setNewOwnerUserDeptId(Long newOwnerUserDeptId) {
		set("new_owner_user_dept_id", newOwnerUserDeptId);
		return (M)this;
	}
	
	public Long getNewOwnerUserDeptId() {
		return getLong("new_owner_user_dept_id");
	}

	public M setNewOwnerUserDeptIdTree(String newOwnerUserDeptIdTree) {
		set("new_owner_user_dept_id_tree", newOwnerUserDeptIdTree);
		return (M)this;
	}
	
	public String getNewOwnerUserDeptIdTree() {
		return getStr("new_owner_user_dept_id_tree");
	}

	public M setNewOwnerUserDeptNameTree(String newOwnerUserDeptNameTree) {
		set("new_owner_user_dept_name_tree", newOwnerUserDeptNameTree);
		return (M)this;
	}
	
	public String getNewOwnerUserDeptNameTree() {
		return getStr("new_owner_user_dept_name_tree");
	}

	public M setOperator(Long operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public Long getOperator() {
		return getLong("operator");
	}

	public M setOperateTime(java.util.Date operateTime) {
		set("operate_time", operateTime);
		return (M)this;
	}
	
	public java.util.Date getOperateTime() {
		return get("operate_time");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
