package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmPerformance<M extends BaseCrmPerformance<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setObjId(Long objId) {
		set("obj_id", objId);
		return (M)this;
	}
	
	public Long getObjId() {
		return getLong("obj_id");
	}

	public M setObjType(Integer objType) {
		set("obj_type", objType);
		return (M)this;
	}
	
	public Integer getObjType() {
		return getInt("obj_type");
	}

	public M setCurrentAmount(java.math.BigDecimal currentAmount) {
		set("current_amount", currentAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getCurrentAmount() {
		return get("current_amount");
	}

	public M setTargetAmount(java.math.BigDecimal targetAmount) {
		set("target_amount", targetAmount);
		return (M)this;
	}
	
	public java.math.BigDecimal getTargetAmount() {
		return get("target_amount");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
