package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmDsk<M extends BaseCrmDsk<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setLoginName(String loginName) {
		set("login_name", loginName);
		return (M)this;
	}

	public String getLoginName() {
		return getStr("login_name");
	}

	public M setDskTotal(Long dskTotal) {
		set("dsk_total", dskTotal);
		return (M)this;
	}

	public Long getDskTotal() {
		return getLong("dsk_total");
	}

	public M setInserviceNum(Long inserviceNum) {
		set("inservice_num", inserviceNum);
		return (M)this;
	}

	public Long getInserviceNum() {
		return getLong("inservice_num");
	}

	public M setInactiveNum(Long inactiveNum) {
		set("inactive_num", inactiveNum);
		return (M)this;
	}

	public Long getInactiveNum() {
		return getLong("inactive_num");
	}

	public M setExpiredNum(Long expiredNum) {
		set("expired_num", expiredNum);
		return (M)this;
	}

	public Long getExpiredNum() {
		return getLong("expired_num");
	}

	public M setHoldNum(Long holdNum) {
		set("hold_num", holdNum);
		return (M)this;
	}

	public Long getHoldNum() {
		return getLong("hold_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setSiteMemberId(Long siteMemberId) {
		set("site_member_id", siteMemberId);
		return (M)this;
	}

	public Long getSiteMemberId() {
		return getLong("site_member_id");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
