package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmDeliveryInformation<M extends BaseCrmDeliveryInformation<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setDeliveryId(String deliveryId) {
		set("delivery_id", deliveryId);
		return (M)this;
	}

	public String getDeliveryId() {
		return getStr("delivery_id");
	}

	public M setOrderNo(String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}

	public String getOrderNo() {
		return getStr("order_no");
	}

	public M setExpressCompany(String expressCompany) {
		set("express_company", expressCompany);
		return (M)this;
	}

	public String getExpressCompany() {
		return getStr("express_company");
	}

	public M setExpressNo(String expressNo) {
		set("express_no", expressNo);
		return (M)this;
	}

	public String getExpressNo() {
		return getStr("express_no");
	}

	public M setHardwareSnNo(String hardwareSnNo) {
		set("hardware_sn_no", hardwareSnNo);
		return (M)this;
	}

	public String getHardwareSnNo() {
		return getStr("hardware_sn_no");
	}

	public M setGoodsName(String goodsName) {
		set("goods_name", goodsName);
		return (M)this;
	}

	public String getGoodsName() {
		return getStr("goods_name");
	}

	public M setGoodsSpec(String goodsSpec) {
		set("goods_spec", goodsSpec);
		return (M)this;
	}

	public String getGoodsSpec() {
		return getStr("goods_spec");
	}

	public M setGoodsCode(String goodsCode) {
		set("goods_code", goodsCode);
		return (M)this;
	}

	public String getGoodsCode() {
		return getStr("goods_code");
	}

	public M setNum(Integer num) {
		set("num", num);
		return (M)this;
	}

	public Integer getNum() {
		return getInt("num");
	}

	public M setOperatorId(Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}

	public Integer getOperatorId() {
		return getInt("operator_id");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

}
