package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseBopsPayment<M extends BaseBopsPayment<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setUserId(String userId) {
		set("user_id", userId);
		return (M)this;
	}

	public String getUserId() {
		return getStr("user_id");
	}

	public M setCrmCustomerId(Integer crmCustomerId) {
		set("crm_customer_id", crmCustomerId);
		return (M)this;
	}

	public Integer getCrmCustomerId() {
		return getInt("crm_customer_id");
	}

	public M setPayName(String payName) {
		set("pay_name", payName);
		return (M)this;
	}

	public String getPayName() {
		return getStr("pay_name");
	}

	public M setTotalAmount(java.math.BigDecimal totalAmount) {
		set("total_amount", totalAmount);
		return (M)this;
	}

	public java.math.BigDecimal getTotalAmount() {
		return get("total_amount");
	}

	public M setSeller(String seller) {
		set("seller", seller);
		return (M)this;
	}

	public String getSeller() {
		return getStr("seller");
	}

	public M setParternAccount(String parternAccount) {
		set("partern_account", parternAccount);
		return (M)this;
	}

	public String getParternAccount() {
		return getStr("partern_account");
	}

	public M setPayType(Integer payType) {
		set("pay_type", payType);
		return (M)this;
	}

	public Integer getPayType() {
		return getInt("pay_type");
	}

	public M setPaymentNo(String paymentNo) {
		set("payment_no", paymentNo);
		return (M)this;
	}

	public String getPaymentNo() {
		return getStr("payment_no");
	}

	public M setPayTime(java.util.Date payTime) {
		set("pay_time", payTime);
		return (M)this;
	}

	public java.util.Date getPayTime() {
		return get("pay_time");
	}

	public M setOuterPaymentNo(String outerPaymentNo) {
		set("outer_payment_no", outerPaymentNo);
		return (M)this;
	}

	public String getOuterPaymentNo() {
		return getStr("outer_payment_no");
	}

	public M setOrderNo(String orderNo) {
		set("order_no", orderNo);
		return (M)this;
	}

	public String getOrderNo() {
		return getStr("order_no");
	}

	public M setComment(String comment) {
		set("comment", comment);
		return (M)this;
	}

	public String getComment() {
		return getStr("comment");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setBopsPaymentId(java.lang.String bopsPaymentId) {
		set("bops_payment_id", bopsPaymentId);
		return (M)this;
	}
	
	public java.lang.String getBopsPaymentId() {
		return getStr("bops_payment_id");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setCrmPayType(Integer payType) {
		set("crm_pay_type", payType);
		return (M)this;
	}

	public Integer getCrmPayType() {
		return getInt("crm_pay_type");
	}
}
