package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmCustomerPaymentChannel<M extends BaseCrmCustomerPaymentChannel<M>> extends CrmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}
	
	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setChannelId(java.lang.String channelId) {
		set("channel_id", channelId);
		return (M)this;
	}
	
	public java.lang.String getChannelId() {
		return getStr("channel_id");
	}

	public M setCrmCustomerId(java.lang.Integer crmCustomerId) {
		set("crm_customer_id", crmCustomerId);
		return (M)this;
	}
	
	public java.lang.Integer getCrmCustomerId() {
		return getInt("crm_customer_id");
	}

	public M setPayType(java.lang.Integer payType) {
		set("pay_type", payType);
		return (M)this;
	}
	
	public java.lang.Integer getPayType() {
		return getInt("pay_type");
	}

	public M setPayName(java.lang.String payName) {
		set("pay_name", payName);
		return (M)this;
	}
	
	public java.lang.String getPayName() {
		return getStr("pay_name");
	}

	public M setPayChannel(java.lang.String payChannel) {
		set("pay_channel", payChannel);
		return (M)this;
	}
	
	public java.lang.String getPayChannel() {
		return getStr("pay_channel");
	}

	public M setChannelName(java.lang.String channelName) {
		set("channel_name", channelName);
		return (M)this;
	}
	
	public java.lang.String getChannelName() {
		return getStr("channel_name");
	}

	public M setParternAccount(java.lang.String parternAccount) {
		set("partern_account", parternAccount);
		return (M)this;
	}
	
	public java.lang.String getParternAccount() {
		return getStr("partern_account");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(java.lang.String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public java.lang.String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

}
