package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmReceivables<M extends BaseCrmReceivables<M>> extends CrmModel<M> implements IBean {

	public M setReceivablesId(Long receivablesId) {
		set("receivables_id", receivablesId);
		return (M)this;
	}

	public Long getReceivablesId() {
		return getLong("receivables_id");
	}

	public M setNumber(String number) {
		set("number", number);
		return (M)this;
	}

	public String getNumber() {
		return getStr("number");
	}

	public M setPlanId(Integer planId) {
		set("plan_id", planId);
		return (M)this;
	}

	public Integer getPlanId() {
		return getInt("plan_id");
	}

	public M setCustomerId(Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}

	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public M setContractId(Integer contractId) {
		set("contract_id", contractId);
		return (M)this;
	}

	public Integer getContractId() {
		return getInt("contract_id");
	}

	public M setCheckStatus(Integer checkStatus) {
		set("check_status", checkStatus);
		return (M)this;
	}

	public Integer getCheckStatus() {
		return getInt("check_status");
	}

	public M setExamineRecordId(Integer examineRecordId) {
		set("examine_record_id", examineRecordId);
		return (M)this;
	}

	public Integer getExamineRecordId() {
		return getInt("examine_record_id");
	}

	public M setReturnTime(java.util.Date returnTime) {
		set("return_time", returnTime);
		return (M)this;
	}

	public java.util.Date getReturnTime() {
		return get("return_time");
	}

	public M setReturnType(String returnType) {
		set("return_type", returnType);
		return (M)this;
	}

	public String getReturnType() {
		return getStr("return_type");
	}

	public M setMoney(java.math.BigDecimal money) {
		set("money", money);
		return (M)this;
	}

	public java.math.BigDecimal getMoney() {
		return get("money");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setOwnerUserId(Integer ownerUserId) {
		set("owner_user_id", ownerUserId);
		return (M)this;
	}

	public Integer getOwnerUserId() {
		return getInt("owner_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setRemarks(String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public String getRemarks() {
		return getStr("remarks");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}

	public String getBatchId() {
		return getStr("batch_id");
	}

	public M setBusinessId(Integer businessId) {
		set("business_id", businessId);
		return (M)this;
	}

	public Integer getBusinessId() {
		return getInt("business_id");
	}

	public M setBopsPaymentId(java.lang.String bopsPaymentId) {
		set("bops_payment_id", bopsPaymentId);
		return (M)this;
	}
	
	public java.lang.String getBopsPaymentId() {
		return getStr("bops_payment_id");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
