package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseDistributorStatistic<M extends BaseDistributorStatistic<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setSiteMemberId(java.lang.Long siteMemberId) {
		set("site_member_id", siteMemberId);
		return (M)this;
	}
	
	public java.lang.Long getSiteMemberId() {
		return getLong("site_member_id");
	}

	public M setProductCode(java.lang.String productCode) {
		set("product_code", productCode);
		return (M)this;
	}
	
	public java.lang.String getProductCode() {
		return getStr("product_code");
	}

	public M setProductName(java.lang.String productName) {
		set("product_name", productName);
		return (M)this;
	}
	
	public java.lang.String getProductName() {
		return getStr("product_name");
	}

	public M setGoodsCode(java.lang.String goodsCode) {
		set("goods_code", goodsCode);
		return (M)this;
	}
	
	public java.lang.String getGoodsCode() {
		return getStr("goods_code");
	}

	public M setGoodsSpec(java.lang.String goodsSpec) {
		set("goods_spec", goodsSpec);
		return (M)this;
	}
	
	public java.lang.String getGoodsSpec() {
		return getStr("goods_spec");
	}

	public M setSalesQuantity(java.lang.Long salesQuantity) {
		set("sales_quantity", salesQuantity);
		return (M)this;
	}
	
	public java.lang.Long getSalesQuantity() {
		return getLong("sales_quantity");
	}

	public M setDeliveryQuantity(java.lang.Long deliveryQuantity) {
		set("delivery_quantity", deliveryQuantity);
		return (M)this;
	}
	
	public java.lang.Long getDeliveryQuantity() {
		return getLong("delivery_quantity");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(java.lang.String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public java.lang.String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(java.lang.String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public java.lang.String getRemark() {
		return getStr("remark");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
