package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmPerformanceLog<M extends BaseCrmPerformanceLog<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}
	
	public String getBatchId() {
		return getStr("batch_id");
	}

	public M setObjId(Long objId) {
		set("obj_id", objId);
		return (M)this;
	}
	
	public Long getObjId() {
		return getLong("obj_id");
	}

	public M setObjType(Integer objType) {
		set("obj_type", objType);
		return (M)this;
	}
	
	public Integer getObjType() {
		return getInt("obj_type");
	}

	public M setCurrentAmountChange(java.math.BigDecimal currentAmountChange) {
		set("current_amount_change", currentAmountChange);
		return (M)this;
	}
	
	public java.math.BigDecimal getCurrentAmountChange() {
		return get("current_amount_change");
	}

	public M setTargetAmountChange(java.math.BigDecimal targetAmountChange) {
		set("target_amount_change", targetAmountChange);
		return (M)this;
	}
	
	public java.math.BigDecimal getTargetAmountChange() {
		return get("target_amount_change");
	}

	public M setFromChannel(String fromChannel) {
		set("from_channel", fromChannel);
		return (M)this;
	}
	
	public String getFromChannel() {
		return getStr("from_channel");
	}

	public M setFromId(Long fromId) {
		set("from_id", fromId);
		return (M)this;
	}
	
	public Long getFromId() {
		return getLong("from_id");
	}

	public M setTargetType(Integer targetType) {
		set("target_type", targetType);
		return (M)this;
	}
	
	public Integer getTargetType() {
		return getInt("target_type");
	}

	public M setTargetId(Long targetId) {
		set("target_id", targetId);
		return (M)this;
	}
	
	public Long getTargetId() {
		return getLong("target_id");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
