package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseMqMsg<M extends BaseMqMsg<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setMsgId(String msgId) {
		set("msg_id", msgId);
		return (M)this;
	}

	public String getMsgId() {
		return getStr("msg_id");
	}

	public M setTopic(String topic) {
		set("topic", topic);
		return (M)this;
	}

	public String getTopic() {
		return getStr("topic");
	}

	public M setTag(String tag) {
		set("tag", tag);
		return (M)this;
	}

	public String getTag() {
		return getStr("tag");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIsConsumed(Integer isConsumed) {
		set("is_consumed", isConsumed);
		return (M)this;
	}

	public Integer getIsConsumed() {
		return getInt("is_consumed");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setMark(String mark) {
		set("mark", mark);
		return (M)this;
	}

	public String getMark() {
		return getStr("mark");
	}

}
