package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmBusinessStatusVerificationRecord<M extends BaseCrmBusinessStatusVerificationRecord<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setBusinessId(Long businessId) {
		set("business_id", businessId);
		return (M)this;
	}
	
	public Long getBusinessId() {
		return getLong("business_id");
	}

	public M setVerificationId(Long verificationId) {
		set("verification_id", verificationId);
		return (M)this;
	}
	
	public Long getVerificationId() {
		return getLong("verification_id");
	}

	public M setStatusId(Long statusId) {
		set("status_id", statusId);
		return (M)this;
	}

	public Long getStatusId() {
		return getLong("status_id");
	}

	public M setBatchId(String batchId) {
		set("batch_id", batchId);
		return (M)this;
	}
	
	public String getBatchId() {
		return getStr("batch_id");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}
	
	public String getContent() {
		return getStr("content");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
