package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmBusinessBelongChangeLog<M extends BaseCrmBusinessBelongChangeLog<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setBusinessId(Long businessId) {
		set("business_id", businessId);
		return (M)this;
	}
	
	public Long getBusinessId() {
		return getLong("business_id");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}
	
	public Integer getType() {
		return getInt("type");
	}

	public M setBdStaffId(Long bdStaffId) {
		set("bd_staff_id", bdStaffId);
		return (M)this;
	}
	
	public Long getBdStaffId() {
		return getLong("bd_staff_id");
	}

	public M setBdStaffAccount(String bdStaffAccount) {
		set("bd_staff_account", bdStaffAccount);
		return (M)this;
	}
	
	public String getBdStaffAccount() {
		return getStr("bd_staff_account");
	}

	public M setDeptId(Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public Long getDeptId() {
		return getLong("dept_id");
	}

	public M setDeptTree(String deptTree) {
		set("dept_tree", deptTree);
		return (M)this;
	}
	
	public String getDeptTree() {
		return getStr("dept_tree");
	}

	public M setOperator(String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public String getOperator() {
		return getStr("operator");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

}
