package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmDistributorPromotionRelation<M extends BaseCrmDistributorPromotionRelation<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setUid(Long uid) {
		set("uid", uid);
		return (M)this;
	}
	
	public Long getUid() {
		return getLong("uid");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public String getUserName() {
		return getStr("user_name");
	}

	public M setRealName(String realName) {
		set("real_name", realName);
		return (M)this;
	}
	
	public String getRealName() {
		return getStr("real_name");
	}

	public M setUserType(Integer userType) {
		set("user_type", userType);
		return (M)this;
	}
	
	public Integer getUserType() {
		return getInt("user_type");
	}

	public M setCertified(Integer certified) {
		set("certified", certified);
		return (M)this;
	}
	
	public Integer getCertified() {
		return getInt("certified");
	}

	public M setPromotionTag(String promotionTag) {
		set("promotion_tag", promotionTag);
		return (M)this;
	}
	
	public String getPromotionTag() {
		return getStr("promotion_tag");
	}

	public M setPUid(Long pUid) {
		set("p_uid", pUid);
		return (M)this;
	}
	
	public Long getPUid() {
		return getLong("p_uid");
	}

	public M setPLevel(Integer pLevel) {
		set("p_level", pLevel);
		return (M)this;
	}
	
	public Integer getPLevel() {
		return getInt("p_level");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
