package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmCustomerExt<M extends BaseCrmCustomerExt<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setCustomerId(Integer customerId) {
		set("customer_id", customerId);
		return (M)this;
	}
	
	public Integer getCustomerId() {
		return getInt("customer_id");
	}

	public M setStorageType(Integer storageType) {
		set("storage_type", storageType);
		return (M)this;
	}
	
	public Integer getStorageType() {
		return getInt("storage_type");
	}

	public M setDrawFlag(Integer drawFlag) {
		set("draw_flag", drawFlag);
		return (M)this;
	}
	
	public Integer getDrawFlag() {
		return getInt("draw_flag");
	}

	public M setLatelyFollowUserId(Integer latelyFollowUserId) {
		set("lately_follow_user_id", latelyFollowUserId);
		return (M)this;
	}

	public Integer getLatelyFollowUserId() {
		return getInt("lately_follow_user_id");
	}

	public M setLatelyFollowTime(java.util.Date latelyFollowTime) {
		set("lately_follow_time", latelyFollowTime);
		return (M)this;
	}

	public java.util.Date getLatelyFollowTime() {
		return get("lately_follow_time");
	}

	public M setOriginalCustomerName(String originalCustomerName) {
		set("original_customer_name", originalCustomerName);
		return (M)this;
	}

	public String getOriginalCustomerName() {
		return getStr("original_customer_name");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public M setParentSiteMemberId(java.lang.Long parentSiteMemberId) {
		set("parent_site_member_id", parentSiteMemberId);
		return (M)this;
	}

	public java.lang.Long getParentSiteMemberId() {
		return getLong("parent_site_member_id");
	}

}
