package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmCustomerSalesLog<M extends BaseCrmCustomerSalesLog<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setLogId(String logId) {
		set("log_id", logId);
		return (M)this;
	}

	public String getLogId() {
		return getStr("log_id");
	}

	public M setCrmCustomerId(Integer crmCustomerId) {
		set("crm_customer_id", crmCustomerId);
		return (M)this;
	}

	public Integer getCrmCustomerId() {
		return getInt("crm_customer_id");
	}

	public M setProductCode(String productCode) {
		set("product_code", productCode);
		return (M)this;
	}

	public String getProductCode() {
		return getStr("product_code");
	}

	public M setProductName(String productName) {
		set("product_name", productName);
		return (M)this;
	}

	public String getProductName() {
		return getStr("product_name");
	}

	public M setGoodsCode(String goodsCode) {
		set("goods_code", goodsCode);
		return (M)this;
	}

	public String getGoodsCode() {
		return getStr("goods_code");
	}

	public M setGoodsSpec(String goodsSpec) {
		set("goods_spec", goodsSpec);
		return (M)this;
	}

	public String getGoodsSpec() {
		return getStr("goods_spec");
	}

	public M setOperationType(Integer operationType) {
		set("operation_type", operationType);
		return (M)this;
	}

	public Integer getOperationType() {
		return getInt("operation_type");
	}

	public M setBdSalesQuantity(Long bdSalesQuantity) {
		set("bd_sales_quantity", bdSalesQuantity);
		return (M)this;
	}

	public Long getBdSalesQuantity() {
		return getLong("bd_sales_quantity");
	}

	public M setBdSalesQuantityValue(Long bdSalesQuantityValue) {
		set("bd_sales_quantity_value", bdSalesQuantityValue);
		return (M)this;
	}

	public Long getBdSalesQuantityValue() {
		return getLong("bd_sales_quantity_value");
	}

	public M setOperatorId(Integer operatorId) {
		set("operator_id", operatorId);
		return (M)this;
	}

	public Integer getOperatorId() {
		return getInt("operator_id");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}

	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}

	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setReduceReasons(java.lang.Integer reduceReasons) {
		set("reduce_reasons", reduceReasons);
		return (M)this;
	}

	public java.lang.Integer getReduceReasons() {
		return getInt("reduce_reasons");
	}

}
