package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * @author system
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmContract<M extends BaseCrmContract<M>> extends CrmModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 合同编号： SC+审核通过时间(14)+四位随机字母(4)
	 */
	public M setContractNum(String contractNum) {
		set("contract_num", contractNum);
		return (M)this;
	}
	
	/**
	 * 合同编号： SC+审核通过时间(14)+四位随机字母(4)
	 */
	public String getContractNum() {
		return getStr("contract_num");
	}

	/**
	 * OA销售合同申请流程编号
	 */
	public M setOaNum(String oaNum) {
		set("oa_num", oaNum);
		return (M)this;
	}
	
	/**
	 * OA销售合同申请流程编号
	 */
	public String getOaNum() {
		return getStr("oa_num");
	}

	/**
	 * OA流程ID
	 */
	public M setRequestId(String requestId) {
		set("request_id", requestId);
		return (M)this;
	}
	
	/**
	 * OA流程ID
	 */
	public String getRequestId() {
		return getStr("request_id");
	}

	/**
	 * 合同名称
	 */
	public M setContractName(String contractName) {
		set("contract_name", contractName);
		return (M)this;
	}
	
	/**
	 * 合同名称
	 */
	public String getContractName() {
		return getStr("contract_name");
	}

	/**
	 * 官网用户ID
	 */
	public M setSiteMemberId(Long siteMemberId) {
		set("site_member_id", siteMemberId);
		return (M)this;
	}
	
	/**
	 * 官网用户ID
	 */
	public Long getSiteMemberId() {
		return getLong("site_member_id");
	}

	/**
	 * 商机ID
	 */
	public M setBusinessId(Long businessId) {
		set("business_id", businessId);
		return (M)this;
	}
	
	/**
	 * 商机ID
	 */
	public Long getBusinessId() {
		return getLong("business_id");
	}

	/**
	 * 合同目的
	 */
	public M setContractTarget(String contractTarget) {
		set("contract_target", contractTarget);
		return (M)this;
	}
	
	/**
	 * 合同目的
	 */
	public String getContractTarget() {
		return getStr("contract_target");
	}

	/**
	 * 合同类型  0 销售合同   1 采购合同   2 合作协议   3 服务   4 研发   5 保密   6 行政合同   7 基站建设合同   8 市场采购-特定合作（暂时限公关部使用）   10 标准电子合同（销售协议）   11 标准电子合同（分销合作协议）   12 标准电子合同（授权服务中心合作协议） 
	 */
	public M setContractType(Integer contractType) {
		set("contract_type", contractType);
		return (M)this;
	}
	
	/**
	 * 合同类型  0 销售合同   1 采购合同   2 合作协议   3 服务   4 研发   5 保密   6 行政合同   7 基站建设合同   8 市场采购-特定合作（暂时限公关部使用）   10 标准电子合同（销售协议）   11 标准电子合同（分销合作协议）   12 标准电子合同（授权服务中心合作协议） 
	 */
	public Integer getContractType() {
		return getInt("contract_type");
	}

	/**
	 * 是否包含保密条款: 0 否 1 是
	 */
	public M setIsSecret(Integer isSecret) {
		set("is_secret", isSecret);
		return (M)this;
	}
	
	/**
	 * 是否包含保密条款: 0 否 1 是
	 */
	public Integer getIsSecret() {
		return getInt("is_secret");
	}

	/**
	 * 合同金额
	 */
	public M setContractMoney(java.math.BigDecimal contractMoney) {
		set("contract_money", contractMoney);
		return (M)this;
	}
	
	/**
	 * 合同金额
	 */
	public java.math.BigDecimal getContractMoney() {
		return get("contract_money");
	}

	/**
	 * 币种： 1 人民币  2 美元  3 港币  4 欧元  5 英镑  6 日元  97 瑞士法郎  98 加拿大元  99 澳大利亚元  100 澳门元  101 新加坡元  102 韩元  103 加元  104 突尼斯第纳尔  105 越南盾  106 印尼盾  107 泰铢  108 菲律宾比索  109 马来西亚林吉特  110 挪威克朗  111 印度卢比
	 */
	public M setCurrencyType(Integer currencyType) {
		set("currency_type", currencyType);
		return (M)this;
	}
	
	/**
	 * 币种： 1 人民币  2 美元  3 港币  4 欧元  5 英镑  6 日元  97 瑞士法郎  98 加拿大元  99 澳大利亚元  100 澳门元  101 新加坡元  102 韩元  103 加元  104 突尼斯第纳尔  105 越南盾  106 印尼盾  107 泰铢  108 菲律宾比索  109 马来西亚林吉特  110 挪威克朗  111 印度卢比
	 */
	public Integer getCurrencyType() {
		return getInt("currency_type");
	}

	/**
	 * 1审核中、2审核通过、3审核未通过 4:作废
	 */
	public M setCheckStatus(Integer checkStatus) {
		set("check_status", checkStatus);
		return (M)this;
	}
	
	/**
	 * 1审核中、2审核通过、3审核未通过 4:作废
	 */
	public Integer getCheckStatus() {
		return getInt("check_status");
	}

	/**
	 * 甲方
	 */
	public M setPartyA(String partyA) {
		set("party_A", partyA);
		return (M)this;
	}
	
	/**
	 * 甲方
	 */
	public String getPartyA() {
		return getStr("party_A");
	}

	/**
	 * 乙方
	 */
	public M setPartyB(String partyB) {
		set("party_B", partyB);
		return (M)this;
	}
	
	/**
	 * 乙方
	 */
	public String getPartyB() {
		return getStr("party_B");
	}

	/**
	 * 丙方
	 */
	public M setPartyC(String partyC) {
		set("party_C", partyC);
		return (M)this;
	}
	
	/**
	 * 丙方
	 */
	public String getPartyC() {
		return getStr("party_C");
	}

	/**
	 * 丁方
	 */
	public M setPartyD(String partyD) {
		set("party_D", partyD);
		return (M)this;
	}
	
	/**
	 * 丁方
	 */
	public String getPartyD() {
		return getStr("party_D");
	}

	/**
	 * 合同期限
	 */
	public M setContractDeadline(String contractDeadline) {
		set("contract_deadline", contractDeadline);
		return (M)this;
	}
	
	/**
	 * 合同期限
	 */
	public String getContractDeadline() {
		return getStr("contract_deadline");
	}

	/**
	 * 收款/付款方式：0 一次性付款 1 分期付款
	 */
	public M setPaymentType(Integer paymentType) {
		set("payment_type", paymentType);
		return (M)this;
	}
	
	/**
	 * 收款/付款方式：0 一次性付款 1 分期付款
	 */
	public Integer getPaymentType() {
		return getInt("payment_type");
	}

	/**
	 * 申请人用户id
	 */
	public M setApplyUserId(Long applyUserId) {
		set("apply_user_id", applyUserId);
		return (M)this;
	}
	
	/**
	 * 申请人用户id
	 */
	public Long getApplyUserId() {
		return getLong("apply_user_id");
	}

	/**
	 * 申请时间（提单时间）
	 */
	public M setApplyTime(java.util.Date applyTime) {
		set("apply_time", applyTime);
		return (M)this;
	}
	
	/**
	 * 申请时间（提单时间）
	 */
	public java.util.Date getApplyTime() {
		return get("apply_time");
	}

	/**
	 * 签订人用户id
	 */
	public M setSignUserId(Long signUserId) {
		set("sign_user_id", signUserId);
		return (M)this;
	}
	
	/**
	 * 签订人用户id
	 */
	public Long getSignUserId() {
		return getLong("sign_user_id");
	}

	/**
	 * 签订部门id
	 */
	public M setSignDeptId(Integer signDeptId) {
		set("sign_dept_id", signDeptId);
		return (M)this;
	}
	
	/**
	 * 签订部门id
	 */
	public Integer getSignDeptId() {
		return getInt("sign_dept_id");
	}

	/**
	 * 审核通过时间
	 */
	public M setExaminePassTime(java.util.Date examinePassTime) {
		set("examine_pass_time", examinePassTime);
		return (M)this;
	}
	
	/**
	 * 审核通过时间
	 */
	public java.util.Date getExaminePassTime() {
		return get("examine_pass_time");
	}

	/**
	 * 附件批次id
	 */
	public M setFileBatchId(String fileBatchId) {
		set("file_batch_id", fileBatchId);
		return (M)this;
	}
	
	/**
	 * 附件批次id
	 */
	public String getFileBatchId() {
		return getStr("file_batch_id");
	}

	/**
	 * 同步状态：0 未同步 1 已同步
	 */
	public M setSyncStatus(Integer syncStatus) {
		set("sync_status", syncStatus);
		return (M)this;
	}
	
	/**
	 * 同步状态：0 未同步 1 已同步
	 */
	public Integer getSyncStatus() {
		return getInt("sync_status");
	}

	/**
	 * 同步时间
	 */
	public M setSyncTime(java.util.Date syncTime) {
		set("sync_time", syncTime);
		return (M)this;
	}
	
	/**
	 * 同步时间
	 */
	public java.util.Date getSyncTime() {
		return get("sync_time");
	}

	/**
	 * 创建时间
	 */
	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	/**
	 * 修改时间
	 */
	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	/**
	 * 0: 未删除 1:已删除
	 */
	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	/**
	 * 0: 未删除 1:已删除
	 */
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 环境标
	 */
	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	/**
	 * 环境标
	 */
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	/**
	 * 备注
	 */
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

}
