package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseSensitiveAccessLog<M extends BaseSensitiveAccessLog<M>> extends CrmModel<M> implements IBean {

	public M setId(java.lang.Long id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Long getId() {
		return getLong("id");
	}

	public M setSecretEntityId(java.lang.Long secretEntityId) {
		set("secret_entity_id", secretEntityId);
		return (M)this;
	}

	public java.lang.Long getSecretEntityId() {
		return getLong("secret_entity_id");
	}

	public M setDataId(java.lang.Long dataId) {
		set("data_id", dataId);
		return (M)this;
	}

	public java.lang.Long getDataId() {
		return getLong("data_id");
	}

	public M setWho(java.lang.String who) {
		set("who", who);
		return (M)this;
	}

	public java.lang.String getWho() {
		return getStr("who");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setIsDeleted(java.lang.Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}

	public java.lang.Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(java.lang.String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}

	public java.lang.String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setMark(java.lang.String mark) {
		set("mark", mark);
		return (M)this;
	}

	public java.lang.String getMark() {
		return getStr("mark");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}

}
