package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseTaskComment<M extends BaseTaskComment<M>> extends CrmModel<M> implements IBean {

	public M setCommentId(Long commentId) {
		set("comment_id", commentId);
		return (M)this;
	}

	public Long getCommentId() {
		return getLong("comment_id");
	}

	public M setUserId(Integer userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Integer getUserId() {
		return getInt("user_id");
	}

	public M setContent(String content) {
		set("content", content);
		return (M)this;
	}

	public String getContent() {
		return getStr("content");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setMainId(Integer mainId) {
		set("main_id", mainId);
		return (M)this;
	}

	public Integer getMainId() {
		return getInt("main_id");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setTypeId(Integer typeId) {
		set("type_id", typeId);
		return (M)this;
	}

	public Integer getTypeId() {
		return getInt("type_id");
	}

	public M setFavour(Integer favour) {
		set("favour", favour);
		return (M)this;
	}

	public Integer getFavour() {
		return getInt("favour");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
