package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmSiteMember<M extends BaseCrmSiteMember<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setSiteMemberId(Long siteMemberId) {
		set("site_member_id", siteMemberId);
		return (M)this;
	}
	
	public Long getSiteMemberId() {
		return getLong("site_member_id");
	}

	public M setCustId(String custId) {
		set("cust_id", custId);
		return (M)this;
	}
	
	public String getCustId() {
		return getStr("cust_id");
	}

	public M setLoginName(String loginName) {
		set("login_name", loginName);
		return (M)this;
	}
	
	public String getLoginName() {
		return getStr("login_name");
	}

	public M setUserType(Integer userType) {
		set("user_type", userType);
		return (M)this;
	}
	
	public Integer getUserType() {
		return getInt("user_type");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public String getUserName() {
		return getStr("user_name");
	}

	public M setEmail(String email) {
		set("email", email);
		return (M)this;
	}
	
	public String getEmail() {
		return getStr("email");
	}

	public M setEmailVerify(Integer emailVerify) {
		set("email_verify", emailVerify);
		return (M)this;
	}
	
	public Integer getEmailVerify() {
		return getInt("email_verify");
	}

	public M setMobile(String mobile) {
		set("mobile", mobile);
		return (M)this;
	}
	
	public String getMobile() {
		return getStr("mobile");
	}

	public M setMobileVerify(Integer mobileVerify) {
		set("mobile_verify", mobileVerify);
		return (M)this;
	}
	
	public Integer getMobileVerify() {
		return getInt("mobile_verify");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setProv(String prov) {
		set("prov", prov);
		return (M)this;
	}
	
	public String getProv() {
		return getStr("prov");
	}

	public M setCity(String city) {
		set("city", city);
		return (M)this;
	}
	
	public String getCity() {
		return getStr("city");
	}

	public M setOptions(String options) {
		set("options", options);
		return (M)this;
	}
	
	public String getOptions() {
		return getStr("options");
	}

	public M setOptionsVer(Long optionsVer) {
		set("options_ver", optionsVer);
		return (M)this;
	}
	
	public Long getOptionsVer() {
		return getLong("options_ver");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public Integer getStatus() {
		return getInt("status");
	}

	public M setRegIp(String regIp) {
		set("reg_ip", regIp);
		return (M)this;
	}
	
	public String getRegIp() {
		return getStr("reg_ip");
	}

	public M setMaxNtripUserNum(Integer maxNtripUserNum) {
		set("max_ntrip_user_num", maxNtripUserNum);
		return (M)this;
	}
	
	public Integer getMaxNtripUserNum() {
		return getInt("max_ntrip_user_num");
	}

	public M setMaxAppNum(Integer maxAppNum) {
		set("max_app_num", maxAppNum);
		return (M)this;
	}
	
	public Integer getMaxAppNum() {
		return getInt("max_app_num");
	}

	public M setNtripUserPrefix(String ntripUserPrefix) {
		set("ntrip_user_prefix", ntripUserPrefix);
		return (M)this;
	}
	
	public String getNtripUserPrefix() {
		return getStr("ntrip_user_prefix");
	}

	public M setNtripPrefixOriginal(String ntripPrefixOriginal) {
		set("ntrip_prefix_original", ntripPrefixOriginal);
		return (M)this;
	}
	
	public String getNtripPrefixOriginal() {
		return getStr("ntrip_prefix_original");
	}

	public M setMonitorPrefix(String monitorPrefix) {
		set("monitor_prefix", monitorPrefix);
		return (M)this;
	}
	
	public String getMonitorPrefix() {
		return getStr("monitor_prefix");
	}

	public M setMonitorPrefixOriginal(String monitorPrefixOriginal) {
		set("monitor_prefix_original", monitorPrefixOriginal);
		return (M)this;
	}
	
	public String getMonitorPrefixOriginal() {
		return getStr("monitor_prefix_original");
	}

	public M setIdNum(String idNum) {
		set("id_num", idNum);
		return (M)this;
	}
	
	public String getIdNum() {
		return getStr("id_num");
	}

	public M setIdImgUrl(String idImgUrl) {
		set("id_img_url", idImgUrl);
		return (M)this;
	}
	
	public String getIdImgUrl() {
		return getStr("id_img_url");
	}

	public M setBusinessLicenceNum(String businessLicenceNum) {
		set("business_licence_num", businessLicenceNum);
		return (M)this;
	}
	
	public String getBusinessLicenceNum() {
		return getStr("business_licence_num");
	}

	public M setBusinessLicenceImgUrl(String businessLicenceImgUrl) {
		set("business_licence_img_url", businessLicenceImgUrl);
		return (M)this;
	}
	
	public String getBusinessLicenceImgUrl() {
		return getStr("business_licence_img_url");
	}

	public M setAuditStatus(Integer auditStatus) {
		set("audit_status", auditStatus);
		return (M)this;
	}
	
	public Integer getAuditStatus() {
		return getInt("audit_status");
	}

	public M setAuditFailureMsg(String auditFailureMsg) {
		set("audit_failure_msg", auditFailureMsg);
		return (M)this;
	}
	
	public String getAuditFailureMsg() {
		return getStr("audit_failure_msg");
	}

	public M setNtripUserCount(Long ntripUserCount) {
		set("ntrip_user_count", ntripUserCount);
		return (M)this;
	}
	
	public Long getNtripUserCount() {
		return getLong("ntrip_user_count");
	}

	public M setIdImgBackUrl(String idImgBackUrl) {
		set("id_img_back_url", idImgBackUrl);
		return (M)this;
	}
	
	public String getIdImgBackUrl() {
		return getStr("id_img_back_url");
	}

	public M setContactor(String contactor) {
		set("contactor", contactor);
		return (M)this;
	}
	
	public String getContactor() {
		return getStr("contactor");
	}

	public M setContactNumber(String contactNumber) {
		set("contact_number", contactNumber);
		return (M)this;
	}
	
	public String getContactNumber() {
		return getStr("contact_number");
	}

	public M setContactAddress(String contactAddress) {
		set("contact_address", contactAddress);
		return (M)this;
	}
	
	public String getContactAddress() {
		return getStr("contact_address");
	}

	public M setContactEmail(String contactEmail) {
		set("contact_email", contactEmail);
		return (M)this;
	}
	
	public String getContactEmail() {
		return getStr("contact_email");
	}

	public M setRealName(String realName) {
		set("real_name", realName);
		return (M)this;
	}
	
	public String getRealName() {
		return getStr("real_name");
	}

	public M setAuditSubmitTime(java.util.Date auditSubmitTime) {
		set("audit_submit_time", auditSubmitTime);
		return (M)this;
	}
	
	public java.util.Date getAuditSubmitTime() {
		return get("audit_submit_time");
	}

	public M setAuditTime(java.util.Date auditTime) {
		set("audit_time", auditTime);
		return (M)this;
	}
	
	public java.util.Date getAuditTime() {
		return get("audit_time");
	}

	public M setTryStatus(Integer tryStatus) {
		set("try_status", tryStatus);
		return (M)this;
	}
	
	public Integer getTryStatus() {
		return getInt("try_status");
	}

	public M setUserFlag(String userFlag) {
		set("user_flag", userFlag);
		return (M)this;
	}
	
	public String getUserFlag() {
		return getStr("user_flag");
	}

	public M setSource(Integer source) {
		set("source", source);
		return (M)this;
	}
	
	public Integer getSource() {
		return getInt("source");
	}

	public M setChannel(String channel) {
		set("channel", channel);
		return (M)this;
	}
	
	public String getChannel() {
		return getStr("channel");
	}

	public M setDevMemo(String devMemo) {
		set("dev_memo", devMemo);
		return (M)this;
	}
	
	public String getDevMemo() {
		return getStr("dev_memo");
	}

	public M setServiceUse(Integer serviceUse) {
		set("service_use", serviceUse);
		return (M)this;
	}
	
	public Integer getServiceUse() {
		return getInt("service_use");
	}

	public M setCustomUse(String customUse) {
		set("custom_use", customUse);
		return (M)this;
	}
	
	public String getCustomUse() {
		return getStr("custom_use");
	}

	public M setAuthSubStatus(Integer authSubStatus) {
		set("auth_sub_status", authSubStatus);
		return (M)this;
	}
	
	public Integer getAuthSubStatus() {
		return getInt("auth_sub_status");
	}

	public M setAuthSubSuffix(String authSubSuffix) {
		set("auth_sub_suffix", authSubSuffix);
		return (M)this;
	}
	
	public String getAuthSubSuffix() {
		return getStr("auth_sub_suffix");
	}

	public M setAuthSubTime(java.util.Date authSubTime) {
		set("auth_sub_time", authSubTime);
		return (M)this;
	}
	
	public java.util.Date getAuthSubTime() {
		return get("auth_sub_time");
	}

	public M setDistributorStatus(Integer distributorStatus) {
		set("distributor_status", distributorStatus);
		return (M)this;
	}
	
	public Integer getDistributorStatus() {
		return getInt("distributor_status");
	}

	public M setBusinessLicenceBegin(java.util.Date businessLicenceBegin) {
		set("business_licence_begin", businessLicenceBegin);
		return (M)this;
	}
	
	public java.util.Date getBusinessLicenceBegin() {
		return get("business_licence_begin");
	}

	public M setBusinessLicenceEnd(java.util.Date businessLicenceEnd) {
		set("business_licence_end", businessLicenceEnd);
		return (M)this;
	}
	
	public java.util.Date getBusinessLicenceEnd() {
		return get("business_licence_end");
	}

	public M setIsDistributor(Integer isDistributor) {
		set("is_distributor", isDistributor);
		return (M)this;
	}
	
	public Integer getIsDistributor() {
		return getInt("is_distributor");
	}

	public M setAddressAreaCode(String addressAreaCode) {
		set("address_area_code", addressAreaCode);
		return (M)this;
	}
	
	public String getAddressAreaCode() {
		return getStr("address_area_code");
	}

	public M setAddressAreaName(String addressAreaName) {
		set("address_area_name", addressAreaName);
		return (M)this;
	}
	
	public String getAddressAreaName() {
		return getStr("address_area_name");
	}

	public M setAddressDetail(String addressDetail) {
		set("address_detail", addressDetail);
		return (M)this;
	}
	
	public String getAddressDetail() {
		return getStr("address_detail");
	}

	public M setAliUid(String aliUid) {
		set("ali_uid", aliUid);
		return (M)this;
	}
	
	public String getAliUid() {
		return getStr("ali_uid");
	}

	public M setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}
	
	public Integer getIsDelete() {
		return getInt("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setLevel(String level) {
		set("level", level);
		return (M)this;
	}
	
	public String getLevel() {
		return getStr("level");
	}

	public M setOperateStatus(Integer operateStatus) {
		set("operate_status", operateStatus);
		return (M)this;
	}
	
	public Integer getOperateStatus() {
		return getInt("operate_status");
	}

	public M setSaleAreaCode(String saleAreaCode) {
		set("sale_area_code", saleAreaCode);
		return (M)this;
	}
	
	public String getSaleAreaCode() {
		return getStr("sale_area_code");
	}

	public M setSaleAreaName(String saleAreaName) {
		set("sale_area_name", saleAreaName);
		return (M)this;
	}
	
	public String getSaleAreaName() {
		return getStr("sale_area_name");
	}

	public M setDataOrigin(String dataOrigin) {
		set("data_origin", dataOrigin);
		return (M)this;
	}
	
	public String getDataOrigin() {
		return getStr("data_origin");
	}

	public M setDistriAuditSuccessTime(java.util.Date distriAuditSuccessTime) {
		set("distri_audit_success_time", distriAuditSuccessTime);
		return (M)this;
	}
	
	public java.util.Date getDistriAuditSuccessTime() {
		return get("distri_audit_success_time");
	}

	public M setDistributorFreeze(Integer distributorFreeze) {
		set("distributor_freeze", distributorFreeze);
		return (M)this;
	}
	
	public Integer getDistributorFreeze() {
		return getInt("distributor_freeze");
	}

	public M setPromotionTag(String promotionTag) {
		set("promotion_tag", promotionTag);
		return (M)this;
	}
	
	public String getPromotionTag() {
		return getStr("promotion_tag");
	}

}
