package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 * @author system
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmContractPayment<M extends BaseCrmContractPayment<M>> extends CrmModel<M> implements IBean {

	/**
	 * 主键id
	 */
	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	/**
	 * 主键id
	 */
	public java.math.BigInteger getId() {
		return get("id");
	}

	/**
	 * 付款编号 : P-19位雪花算法
	 */
	public M setPaymentCode(String paymentCode) {
		set("payment_code", paymentCode);
		return (M)this;
	}
	
	/**
	 * 付款编号 : P-19位雪花算法
	 */
	public String getPaymentCode() {
		return getStr("payment_code");
	}

	/**
	 * 合同ID
	 */
	public M setContractId(java.math.BigInteger contractId) {
		set("contract_id", contractId);
		return (M)this;
	}
	
	/**
	 * 合同ID
	 */
	public java.math.BigInteger getContractId() {
		return get("contract_id");
	}

	/**
	 * 回款计划ID
	 */
	public M setPlanId(Long planId) {
		set("plan_id", planId);
		return (M)this;
	}
	
	/**
	 * 回款计划ID
	 */
	public Long getPlanId() {
		return getLong("plan_id");
	}

	/**
	 * 期数:指在该合同中的付款条款的顺序
	 */
	public M setNum(Integer num) {
		set("num", num);
		return (M)this;
	}
	
	/**
	 * 期数:指在该合同中的付款条款的顺序
	 */
	public Integer getNum() {
		return getInt("num");
	}

	/**
	 * 付款条件
	 */
	public M setPaymentCondition(String paymentCondition) {
		set("payment_condition", paymentCondition);
		return (M)this;
	}
	
	/**
	 * 付款条件
	 */
	public String getPaymentCondition() {
		return getStr("payment_condition");
	}

	/**
	 * 付款日期
	 */
	public M setPaymentDate(java.util.Date paymentDate) {
		set("payment_date", paymentDate);
		return (M)this;
	}
	
	/**
	 * 付款日期
	 */
	public java.util.Date getPaymentDate() {
		return get("payment_date");
	}

	/**
	 * 计算方式 0 按金额  1 按比例
	 */
	public M setComputeMode(Integer computeMode) {
		set("compute_mode", computeMode);
		return (M)this;
	}
	
	/**
	 * 计算方式 0 按金额  1 按比例
	 */
	public Integer getComputeMode() {
		return getInt("compute_mode");
	}

	/**
	 * 付款金额
	 */
	public M setPaymentMoney(java.math.BigDecimal paymentMoney) {
		set("payment_money", paymentMoney);
		return (M)this;
	}
	
	/**
	 * 付款金额
	 */
	public java.math.BigDecimal getPaymentMoney() {
		return get("payment_money");
	}

	/**
	 * 单位： 1 人民币  2 美元  3 港币  4 欧元  5 英镑  6 日元  97 瑞士法郎  98 加拿大元  99 澳大利亚元  100 澳门元  101 新加坡元  102 韩元  103 加元  104 突尼斯第纳尔  105 越南盾  106 印尼盾  107 泰铢  108 菲律宾比索  109 马来西亚林吉特  110 挪威克朗  111 印度卢比
	 */
	public M setUnit(Integer unit) {
		set("unit", unit);
		return (M)this;
	}
	
	/**
	 * 单位： 1 人民币  2 美元  3 港币  4 欧元  5 英镑  6 日元  97 瑞士法郎  98 加拿大元  99 澳大利亚元  100 澳门元  101 新加坡元  102 韩元  103 加元  104 突尼斯第纳尔  105 越南盾  106 印尼盾  107 泰铢  108 菲律宾比索  109 马来西亚林吉特  110 挪威克朗  111 印度卢比
	 */
	public Integer getUnit() {
		return getInt("unit");
	}

	/**
	 * 创建时间
	 */
	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	/**
	 * 创建时间
	 */
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	/**
	 * 修改时间
	 */
	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	/**
	 * 修改时间
	 */
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	/**
	 * 0: 未删除 1:已删除
	 */
	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	/**
	 * 0: 未删除 1:已删除
	 */
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	/**
	 * 环境标
	 */
	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	/**
	 * 环境标
	 */
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	/**
	 * 备注
	 */
	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	/**
	 * 备注
	 */
	public String getRemark() {
		return getStr("remark");
	}

}
