package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmDeptChangeLog<M extends BaseCrmDeptChangeLog<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setDeptId(Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public Long getDeptId() {
		return getLong("dept_id");
	}

	public M setLevel(Integer level) {
		set("level", level);
		return (M)this;
	}
	
	public Integer getLevel() {
		return getInt("level");
	}

	public M setPDeptId(Long pDeptId) {
		set("p_dept_id", pDeptId);
		return (M)this;
	}
	
	public Long getPDeptId() {
		return getLong("p_dept_id");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}
	
	public Integer getStatus() {
		return getInt("status");
	}

	public M setDeptTree(String deptTree) {
		set("dept_tree", deptTree);
		return (M)this;
	}
	
	public String getDeptTree() {
		return getStr("dept_tree");
	}

	public M setOperator(String operator) {
		set("operator", operator);
		return (M)this;
	}
	
	public String getOperator() {
		return getStr("operator");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

}
