package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmLabel<M extends BaseCrmLabel<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}
	
	public Long getId() {
		return getLong("id");
	}

	public M setRelatedId(Long relatedId) {
		set("related_id", relatedId);
		return (M)this;
	}
	
	public Long getRelatedId() {
		return getLong("related_id");
	}

	public M setRelatedType(Integer relatedType) {
		set("related_type", relatedType);
		return (M)this;
	}
	
	public Integer getRelatedType() {
		return getInt("related_type");
	}

	public M setLabelKey(Integer labelKey) {
		set("label_key", labelKey);
		return (M)this;
	}
	
	public Integer getLabelKey() {
		return getInt("label_key");
	}

	public M setLabelValue(Integer labelValue) {
		set("label_value", labelValue);
		return (M)this;
	}
	
	public Integer getLabelValue() {
		return getInt("label_value");
	}

	public M setLabelComment(String labelComment) {
		set("label_comment", labelComment);
		return (M)this;
	}
	
	public String getLabelComment() {
		return getStr("label_comment");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

	public M setAuthUserId(java.lang.Integer authUserId) {
		set("auth_user_id", authUserId);
		return (M)this;
	}

	public java.lang.Integer getAuthUserId() {
		return getInt("auth_user_id");
	}

	public M setAuthDeptId(java.lang.Integer authDeptId) {
		set("auth_dept_id", authDeptId);
		return (M)this;
	}

	public java.lang.Integer getAuthDeptId() {
		return getInt("auth_dept_id");
	}
}
