package com.kakarote.crm9.erp.crm.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmBusinessChange<M extends BaseCrmBusinessChange<M>> extends CrmModel<M> implements IBean {

	public M setChangeId(Integer changeId) {
		set("change_id", changeId);
		return (M)this;
	}

	public Integer getChangeId() {
		return getInt("change_id");
	}

	public M setBusinessId(Integer businessId) {
		set("business_id", businessId);
		return (M)this;
	}

	public Integer getBusinessId() {
		return getInt("business_id");
	}

	public M setStatusId(Integer statusId) {
		set("status_id", statusId);
		return (M)this;
	}

	public Integer getStatusId() {
		return getInt("status_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
