package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BaseAdminLookUpLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminLookUpLog extends BaseAdminLookUpLog<AdminLookUpLog> {
	public static final AdminLookUpLog dao = new AdminLookUpLog().dao();
}
