package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminDeptCapacity;

/**
 * Generated by JFinal.
 * @author haihong.wu
 */
@SuppressWarnings("serial")
public class AdminDeptCapacity extends BaseAdminDeptCapacity<AdminDeptCapacity> {
	public static final AdminDeptCapacity dao = new AdminDeptCapacity().dao();
}
