package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminDataDic;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminDataDic extends BaseAdminDataDic<AdminDataDic> {
	public static final AdminDataDic dao = new AdminDataDic().dao();
}
