package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminScenario;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminScenario extends BaseAdminScenario<AdminScenario> {
	public static final AdminScenario dao = new AdminScenario().dao();

}
