package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BaseAdminIndustryOfDept;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminIndustryOfDept extends BaseAdminIndustryOfDept<AdminIndustryOfDept> {
	public static final AdminIndustryOfDept dao = new AdminIndustryOfDept().dao();
}
