package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BaseAdminCustomerReceiveRole;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminCustomerReceiveRole extends BaseAdminCustomerReceiveRole<AdminCustomerReceiveRole> {
	public static final AdminCustomerReceiveRole dao = new AdminCustomerReceiveRole().dao();
}
