package com.kakarote.crm9.erp.admin.entity;


import com.jfinal.plugin.activerecord.Db;
import com.kakarote.crm9.common.constant.BaseConstant;
import com.kakarote.crm9.erp.admin.entity.base.BaseAdminConfig;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminConfig extends BaseAdminConfig<AdminConfig> {
    public static final AdminConfig dao = new AdminConfig().dao();

    public AdminConfig findByName(String name) {
        return dao.findFirst(Db.getSql("admin.config.adminConfigByName"), BaseConstant.OpenState.OPEN, name);
    }
}
