package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseAdminUserCapacity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminUserCapacity extends BaseAdminUserCapacity<AdminUserCapacity> {
	public static final AdminUserCapacity dao = new AdminUserCapacity().dao();
}
