package com.kakarote.crm9.erp.admin.entity;


import com.kakarote.crm9.erp.admin.entity.base.BaseAdminBusinessStatusType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AdminBusinessStatusType extends BaseAdminBusinessStatusType<AdminBusinessStatusType> {
	public static final AdminBusinessStatusType dao = new AdminBusinessStatusType().dao();
}
