package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseCrmBusinessStatusVerification;

/**
 * Generated by JFinal.
 * @author liming.guo
 */
@SuppressWarnings("serial")
public class CrmBusinessStatusVerification extends BaseCrmBusinessStatusVerification<CrmBusinessStatusVerification> {
	public static final CrmBusinessStatusVerification dao = new CrmBusinessStatusVerification().dao();
}
