package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseCrmBusinessGroup;

/**
 * Generated by JFinal.
 * @author liming.guo
 */
@SuppressWarnings("serial")
public class CrmBusinessGroup extends BaseCrmBusinessGroup<CrmBusinessGroup> {
	public static final CrmBusinessGroup dao = new CrmBusinessGroup().dao();
}
