package com.kakarote.crm9.erp.admin.entity;

import com.kakarote.crm9.erp.admin.entity.base.BaseCrmBusinessStatusSalesActivity;

/**
 * Generated by JFinal.
 * @author liming.guo
 */
@SuppressWarnings("serial")
public class CrmBusinessStatusSalesActivity extends BaseCrmBusinessStatusSalesActivity<CrmBusinessStatusSalesActivity> {
	public static final CrmBusinessStatusSalesActivity dao = new CrmBusinessStatusSalesActivity().dao();
}
