package com.kakarote.crm9.erp.crm.entity;


import com.jfinal.kit.JsonKit;
import com.kakarote.crm9.erp.crm.entity.base.BaseBopsPayment;

/**
 * Generated by JFinal.
 * @author honglei.wan
 */
@SuppressWarnings("serial")
public class BopsPayment extends BaseBopsPayment<BopsPayment> {
	public static final BopsPayment dao = new BopsPayment().dao();

	@Override
	public String toString() {
		return JsonKit.toJson(this);
	}

	@Override
	public int hashCode() {
		return super.hashCode();
	}

	@Override
	public boolean equals(Object o) {
		return super.equals(o);
	}
}
