package com.kakarote.crm9.erp.crm.entity;

import com.alibaba.fastjson.JSON;
import com.kakarote.crm9.erp.crm.entity.base.BaseCrmActionRecord;

import java.util.ArrayList;
import java.util.Date;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmActionRecord extends BaseCrmActionRecord<CrmActionRecord> {

	/**
	 * @param createUserId 创建人id
	 * @param types	业务类型
	 * @param actionId	业务主键
	 * @param content	操作内容
	 */
	public CrmActionRecord(Integer createUserId ,String types, Integer actionId, String content){
		setCreateUserId(createUserId);
		setTypes(types);
		setActionId(actionId);
		ArrayList<String> strings = new ArrayList<>();
		strings.add(content);
		setContent(JSON.toJSONString(strings));
		setCreateTime(new Date());
		setUpdateTime(new Date());
	}
	public CrmActionRecord(){

	}

	public static final CrmActionRecord dao = new CrmActionRecord().dao();
}
