package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBusinessProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessProduct extends BaseCrmBusinessProduct<CrmBusinessProduct> {
	public static final CrmBusinessProduct dao = new CrmBusinessProduct().dao();

	private String categoryCode;

	private String categoryName;

	/** 商品编码 */
	private String code;

	/** 商品名称 */
	private String name;

	/**业务主键ID*/
	private String id;

	public String getCategoryCode() {
		return categoryCode;
	}

	public void setCategoryCode(String categoryCode) {
		this.categoryCode = categoryCode;
	}

	public String getCategoryName() {
		return categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	public String getCode() {
		return code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getId() { return id; }

	public void setId(String id) { this.id = id; }
}
