package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBusinessStatusVerificationRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessStatusVerificationRecord extends BaseCrmBusinessStatusVerificationRecord<CrmBusinessStatusVerificationRecord> {
	public static final CrmBusinessStatusVerificationRecord dao = new CrmBusinessStatusVerificationRecord().dao();
}
