package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBdDeptChangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBdDeptChangeLog extends BaseCrmBdDeptChangeLog<CrmBdDeptChangeLog> {
	public static final CrmBdDeptChangeLog dao = new CrmBdDeptChangeLog().dao();
}
