package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBusinessStatusSalesActivityRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessStatusSalesActivityRecord extends BaseCrmBusinessStatusSalesActivityRecord<CrmBusinessStatusSalesActivityRecord> {
	public static final CrmBusinessStatusSalesActivityRecord dao = new CrmBusinessStatusSalesActivityRecord().dao();
}
