package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBatchRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBatchRecord extends BaseCrmBatchRecord<CrmBatchRecord> {
	public static final CrmBatchRecord dao = new CrmBatchRecord().dao();
}
