package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmBusinessBelongChangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmBusinessBelongChangeLog extends BaseCrmBusinessBelongChangeLog<CrmBusinessBelongChangeLog> {
	public static final CrmBusinessBelongChangeLog dao = new CrmBusinessBelongChangeLog().dao();
}
