package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmContractPayment;
import lombok.Getter;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

/**
 * Generated by JFinal.
 * @author honglei.wan
 */
@Getter
@NoArgsConstructor
public class CrmContractPayment extends BaseCrmContractPayment<CrmContractPayment> {
	public static final CrmContractPayment dao = new CrmContractPayment().dao();
	private static final long serialVersionUID = -3262891932845450310L;

	/**
	 * 回款进度
	 */
	private String paymentProgress;

	/**
	 * 已回款金额
	 */
	private BigDecimal paidAmount;

	/**
	 * 待回款金额
	 */
	private BigDecimal unPaidAmount;

	/**
	 * 最新回款日期
	 */
	private Date lastPayTime;

	public void setPaymentProgress(String paymentProgress) {
		this.paymentProgress = paymentProgress;
		put("payment_progress", paymentProgress);
	}

	public void setPaidAmount(BigDecimal paidAmount) {
		this.paidAmount = paidAmount;
		put("paid_amount", paidAmount);
	}

	public void setUnPaidAmount(BigDecimal unPaidAmount) {
		this.unPaidAmount = unPaidAmount;
		put("un_paid_amount", unPaidAmount);
	}

	public void setLastPayTime(Date lastPayTime) {
		this.lastPayTime = lastPayTime;
		put("last_pay_time", lastPayTime);
	}

	/**
	 * 根据付款条款编号查询付款条款
	 * @param paymentCode
	 * @return
	 */
	public CrmContractPayment getByPaymentCode(String paymentCode) {
		return dao.findSingleByColumn("payment_code", paymentCode);
	}

	/**
	 * 根据合同ID查询付款条款列表
	 * @param contractId
	 * @return
	 */
	public List<CrmContractPayment> listByContractId(Long contractId) {
		return CrmContractPayment.dao.findListByColumn("contract_id", contractId);
	}
}
