package com.kakarote.crm9.erp.crm.entity;


import com.jfinal.plugin.activerecord.Db;
import com.kakarote.crm9.erp.crm.entity.base.BaseCrmContractProduct;
import lombok.Getter;

import java.math.BigDecimal;
import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
@Getter
public class CrmContractProduct extends BaseCrmContractProduct<CrmContractProduct> {
    public static final CrmContractProduct dao = new CrmContractProduct().dao();

    private String productType;
    private String productName;
    private Integer productNum;
    private BigDecimal productMoney;
    /**
     * 产品code，对应产品表code
     */
    private String productCode;

    /**
     * 根据合同ID查询合同关联的产品详情列表
     *
     * @param contractId
     * @return
     */
    public List<CrmContractProduct> queryProductDetailByContractId(Long contractId) {
        return CrmContractProduct.dao.find(Db.getSql("crm.contract.product.queryProductDetailByContractId"), contractId);
    }

    public void setProductType(String productType) {
        this.productType = productType;
        put("product_type", productType);
    }

    public void setProductName(String productName) {
        this.productName = productName;
        put("product_name", productName);
    }

    public void setProductNum(Integer productNum) {
        this.productNum = productNum;
        put("product_num", productNum);
    }

    public void setProductMoney(BigDecimal productMoney) {
        this.productMoney = productMoney;
        put("product_money", productMoney);
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }
}
