package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerBelongChangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerBelongChangeLog extends BaseCrmCustomerBelongChangeLog<CrmCustomerBelongChangeLog> {
	public static final CrmCustomerBelongChangeLog dao = new CrmCustomerBelongChangeLog().dao();
}
