package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerAddressHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerAddressHistory extends BaseCrmCustomerAddressHistory<CrmCustomerAddressHistory> {
	public static final CrmCustomerAddressHistory dao = new CrmCustomerAddressHistory().dao();
}
