package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCallContactRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCallContactRelation extends BaseCrmCallContactRelation<CrmCallContactRelation> {
	public static final CrmCallContactRelation dao = new CrmCallContactRelation().dao();
}
