package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerPaymentChannel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerPaymentChannel extends BaseCrmCustomerPaymentChannel<CrmCustomerPaymentChannel> {
	public static final CrmCustomerPaymentChannel dao = new CrmCustomerPaymentChannel().dao();
}
