package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCallRecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCallRecord extends BaseCrmCallRecord<CrmCallRecord> {
	public static final CrmCallRecord dao = new CrmCallRecord().dao();
}
