package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmChangeLog;

/**
 * Generated by JFinal.
 * 变化历史记录表
 */
@SuppressWarnings("serial")
public class CrmChangeLog extends BaseCrmChangeLog<CrmChangeLog> {
    public static final CrmChangeLog dao = new CrmChangeLog().dao();
}
