package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmCustomerSalesLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmCustomerSalesLog extends BaseCrmCustomerSalesLog<CrmCustomerSalesLog> {
	public static final CrmCustomerSalesLog dao = new CrmCustomerSalesLog().dao();
}
