package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmDeptChangeLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDeptChangeLog extends BaseCrmDeptChangeLog<CrmDeptChangeLog> {
	public static final CrmDeptChangeLog dao = new CrmDeptChangeLog().dao();
}
