package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmDistributorPromotionRelation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDistributorPromotionRelation extends BaseCrmDistributorPromotionRelation<CrmDistributorPromotionRelation> {
	public static final CrmDistributorPromotionRelation dao = new CrmDistributorPromotionRelation().dao();
}
