package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmDistributeDeptThreshold;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDistributeDeptThreshold extends BaseCrmDistributeDeptThreshold<CrmDistributeDeptThreshold> {
	public static final CrmDistributeDeptThreshold dao = new CrmDistributeDeptThreshold().dao();
}
