package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmDsk;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDsk extends BaseCrmDsk<CrmDsk> {
	public static final CrmDsk dao = new CrmDsk().dao();
}
