package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmDeliveryInformation;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmDeliveryInformation extends BaseCrmDeliveryInformation<CrmDeliveryInformation> {
	public static final CrmDeliveryInformation dao = new CrmDeliveryInformation().dao();
}
