package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmGroupMember;

/**
 * Generated by JFinal.
 * @author haihong.wu
 */
@SuppressWarnings("serial")
public class CrmGroupMember extends BaseCrmGroupMember<CrmGroupMember> {
	public static final CrmGroupMember dao = new CrmGroupMember().dao();
}
