package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmLabel;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmLabel extends BaseCrmLabel<CrmLabel> {
	public static final CrmLabel dao = new CrmLabel().dao();
}
