package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmPerformanceLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmPerformanceLog extends BaseCrmPerformanceLog<CrmPerformanceLog> {
	public static final CrmPerformanceLog dao = new CrmPerformanceLog().dao();
}
