package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmPerformance;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmPerformance extends BaseCrmPerformance<CrmPerformance> {
	public static final CrmPerformance dao = new CrmPerformance().dao();
}
