package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmPrivateTag;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmPrivateTag extends BaseCrmPrivateTag<CrmPrivateTag> {
	public static final CrmPrivateTag dao = new CrmPrivateTag().dao();
}
