package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmReceivables;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivables extends BaseCrmReceivables<CrmReceivables> {
	public static final CrmReceivables dao = new CrmReceivables().dao();

	private String businessProds;
	/**
	 * 是否关联合同，0 否，1 是
	 */
	private String hasReleativeContract;
	
	/**
	 * 合同id，多个逗号连接
	 */
	private String contractIds;

	public String getBusinessProds() {
		return businessProds;
	}

	public void setBusinessProds(String businessProds) {
		this.businessProds = businessProds;
	}

	public String getHasReleativeContract() {
		return hasReleativeContract;
	}

	public void setHasReleativeContract(String hasReleativeContract) {
		this.hasReleativeContract = hasReleativeContract;
	}

	public String getContractIds() {
		return contractIds;
	}

	public void setContractIds(String contractIds) {
		this.contractIds = contractIds;
	}
	
}
