package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmReceivablesPlanProduct;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivablesPlanProduct extends BaseCrmReceivablesPlanProduct<CrmReceivablesPlanProduct> {
	public static final CrmReceivablesPlanProduct dao = new CrmReceivablesPlanProduct().dao();
}
