package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseCrmReceivablesPlan;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmReceivablesPlan extends BaseCrmReceivablesPlan<CrmReceivablesPlan> {
	public static final CrmReceivablesPlan dao = new CrmReceivablesPlan().dao();

	private String businessProds;

	public String getBusinessProds() {
		return businessProds;
	}

	public void setBusinessProds(String businessProds) {
		this.businessProds = businessProds;
	}
}
