package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmSignInHistory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmSignInHistory extends BaseCrmSignInHistory<CrmSignInHistory> {
	public static final CrmSignInHistory dao = new CrmSignInHistory().dao();
}
