package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseCrmSiteMember;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CrmSiteMember extends BaseCrmSiteMember<CrmSiteMember> {
	public static final CrmSiteMember dao = new CrmSiteMember().dao();
}
