package com.kakarote.crm9.erp.crm.entity;

import com.jfinal.kit.JsonKit;
import com.kakarote.crm9.common.annotation.ModelData;
import com.kakarote.crm9.erp.crm.entity.base.BaseDistributorStatistic;

import java.util.Objects;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class DistributorStatistic extends BaseDistributorStatistic<DistributorStatistic> {
    public static final DistributorStatistic dao = new DistributorStatistic().dao();

    /**
     * BD跟进的销售数量
     */
    @ModelData
    private int bdSalesQuantity;

    /**
     * 理论库存 = 采购数量 - BD跟进的销售数量
     */
    @ModelData
    private int theoryStock;

    /**
     * 真实库存 = 已发货数量 - BD跟进的销售数量
     */
    @ModelData
    private int actualStock;

    public int getBdSalesQuantity() {
        return bdSalesQuantity;
    }

    public void setBdSalesQuantity(int bdSalesQuantity) {
        this.bdSalesQuantity = bdSalesQuantity;
    }

    public int getTheoryStock() {
        return theoryStock;
    }

    public void setTheoryStock() {
        if (Objects.nonNull(getSalesQuantity())) {
            theoryStock = getSalesQuantity().intValue() - getBdSalesQuantity();
        } else {
            theoryStock = 0;
        }
    }

    public int getActualStock() {
        return actualStock;
    }

    public void setActualStock() {
        if (Objects.nonNull(getDeliveryQuantity())) {
            actualStock = getDeliveryQuantity().intValue() - getBdSalesQuantity();
        } else {
            actualStock = 0;
        }
    }

    @Override
    public String toString() {
        return JsonKit.toJson(this);
    }
}
