package com.kakarote.crm9.erp.crm.entity;


import com.kakarote.crm9.erp.crm.entity.base.BaseMqMsg;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class MqMsg extends BaseMqMsg<MqMsg> {
	public static final MqMsg dao = new MqMsg().dao();
}
