package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseSensitiveEntity;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensitiveEntity extends BaseSensitiveEntity<SensitiveEntity> {
	public static final SensitiveEntity dao = new SensitiveEntity().dao();
}
