package com.kakarote.crm9.erp.crm.entity;

import com.kakarote.crm9.erp.crm.entity.base.BaseSensitiveAccessLog;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SensitiveAccessLog extends BaseSensitiveAccessLog<SensitiveAccessLog> {
	public static final SensitiveAccessLog dao = new SensitiveAccessLog().dao();
}
