package com.kakarote.crm9.erp;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;
import com.kakarote.crm9.erp.admin.entity.*;
import com.kakarote.crm9.erp.crm.entity.*;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 * @author honglei.wan
 */
public class MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("72crm_admin_dept", "id", AdminDept.class);
		arp.addMapping("72crm_admin_config", "setting_id", AdminConfig.class);
		arp.addMapping("72crm_admin_field", "field_id", AdminField.class);
		arp.addMapping("72crm_admin_field_sort", "field_id", AdminFieldSort.class);
		arp.addMapping("72crm_admin_field_style", "id", AdminFieldStyle.class);
		arp.addMapping("72crm_admin_file", "file_id", AdminFile.class);
		arp.addMapping("72crm_admin_menu", "menu_id", AdminMenu.class);
		arp.addMapping("72crm_admin_record", "record_id", AdminRecord.class);
		arp.addMapping("72crm_admin_role", "role_id", AdminRole.class);
		arp.addMapping("72crm_admin_role_menu", "id", AdminRoleMenu.class);
		arp.addMapping("72crm_admin_scene", "scene_id", AdminScene.class);
		arp.addMapping("72crm_admin_scene_default", "default_id", AdminSceneDefault.class);
		arp.addMapping("72crm_admin_user", "id", AdminUser.class);
		arp.addMapping("72crm_admin_user_role", "id", AdminUserRole.class);
		arp.addMapping("72crm_admin_scenario", "scenario_id", AdminScenario.class);
		arp.addMapping("72crm_admin_data_dic", "dic_id", AdminDataDic.class);
        arp.addMapping("72crm_admin_look_up_log", "log_id", AdminLookUpLog.class);
        arp.addMapping("72crm_admin_business_status_type", "id", AdminBusinessStatusType.class);
		arp.addMapping("72crm_crm_batch_record", "batch_id", CrmBatchRecord.class);
		arp.addMapping("72crm_crm_business", "business_id", CrmBusiness.class);
		arp.addMapping("72crm_crm_achievement", "achievement_id", CrmAchievement.class);
		arp.addMapping("72crm_crm_action_record", "id", CrmActionRecord.class);
		arp.addMapping("72crm_crm_business_product", "r_id", CrmBusinessProduct.class);
		arp.addMapping("72crm_crm_business_status", "status_id", CrmBusinessStatus.class);
		arp.addMapping("72crm_crm_business_type", "type_id", CrmBusinessType.class);
		arp.addMapping("72crm_crm_call_contact_relation", "id", CrmCallContactRelation.class);
		arp.addMapping("72crm_crm_call_record", "id", CrmCallRecord.class);
		arp.addMapping("72crm_crm_contacts", "contacts_id", CrmContacts.class);
		arp.addMapping("72crm_crm_contacts_business", "id", CrmContactsBusiness.class);
		arp.addMapping("72crm_crm_contract", "id", CrmContract.class);
		arp.addMapping("72crm_crm_contract_payment", "id", CrmContractPayment.class);
		arp.addMapping("72crm_crm_contract_product", "id", CrmContractProduct.class);
		arp.addMapping("72crm_crm_customer", "customer_id", CrmCustomer.class);
		arp.addMapping("72crm_crm_customer_stats", "id", CrmCustomerStats.class);
		arp.addMapping("72crm_crm_leads", "leads_id", CrmLeads.class);
		arp.addMapping("72crm_crm_owner_record", "record_id", CrmOwnerRecord.class);
		arp.addMapping("72crm_crm_product", "product_id", CrmProduct.class);
		arp.addMapping("72crm_crm_product_category", "category_id", CrmProductCategory.class);
		arp.addMapping("72crm_crm_receivables", "receivables_id", CrmReceivables.class);
		arp.addMapping("72crm_crm_receivables_plan", "plan_id", CrmReceivablesPlan.class);
		arp.addMapping("72crm_task_comment", "comment_id", TaskComment.class);
		arp.addMapping("72crm_crm_business_change", "change_id", CrmBusinessChange.class);
		arp.addMapping("72crm_crm_site_member", "id", CrmSiteMember.class);
		arp.addMapping("72crm_crm_dsk", "id", CrmDsk.class);
		arp.addMapping("72crm_sensitive_entity", "id", SensitiveEntity.class);
		arp.addMapping("72crm_sensitive_access_log", "id", SensitiveAccessLog.class);
		arp.addMapping("72crm_mq_msg", "id", MqMsg.class);
		arp.addMapping("72crm_crm_receivables_plan_product", "id", CrmReceivablesPlanProduct.class);
		arp.addMapping("72crm_crm_private_tag", "id", CrmPrivateTag.class);
		arp.addMapping("72crm_bops_payment", "id", BopsPayment.class);
		arp.addMapping("72crm_crm_customer_payment_channel", "id", CrmCustomerPaymentChannel.class);
		arp.addMapping("72crm_crm_delivery_information", "id", CrmDeliveryInformation.class);
		arp.addMapping("72crm_crm_customer_sales_log", "id", CrmCustomerSalesLog.class);
		arp.addMapping("72crm_distributor_statistic", "id", DistributorStatistic.class);
		arp.addMapping("72crm_crm_customer_address_history", "id", CrmCustomerAddressHistory.class);
		arp.addMapping("72crm_crm_sign_in_history", "id", CrmSignInHistory.class);
		arp.addMapping("72crm_crm_label", "id", CrmLabel.class);
		arp.addMapping("72crm_admin_industry_of_dept", "id", AdminIndustryOfDept.class);
		arp.addMapping("72crm_crm_performance", "id", CrmPerformance.class);
		arp.addMapping("72crm_crm_performance_log", "id", CrmPerformanceLog.class);
		arp.addMapping("72crm_admin_dept_capacity", "id", AdminDeptCapacity.class);
		arp.addMapping("72crm_admin_user_capacity", "id", AdminUserCapacity.class);
		arp.addMapping("72crm_crm_customer_ext", "id", CrmCustomerExt.class);
		arp.addMapping("72crm_admin_customer_receive_role", "id", AdminCustomerReceiveRole.class);
		arp.addMapping("72crm_crm_change_log", "id", CrmChangeLog.class);
		arp.addMapping("72crm_crm_business_group", "id", CrmBusinessGroup.class);
		arp.addMapping("72crm_crm_business_status_sales_activity", "id", CrmBusinessStatusSalesActivity.class);
		arp.addMapping("72crm_crm_business_status_verification", "id", CrmBusinessStatusVerification.class);
		arp.addMapping("72crm_crm_business_status_sales_activity_record", "id", CrmBusinessStatusSalesActivityRecord.class);
		arp.addMapping("72crm_crm_business_status_verification_record", "id", CrmBusinessStatusVerificationRecord.class);
		arp.addMapping("crm_customer_belong_change_log", "id", CrmCustomerBelongChangeLog.class);
		arp.addMapping("crm_business_belong_change_log", "id", CrmBusinessBelongChangeLog.class);
		arp.addMapping("crm_bd_dept_change_log", "id", CrmBdDeptChangeLog.class);
		arp.addMapping("crm_dept_change_log", "id", CrmDeptChangeLog.class);
		arp.addMapping("72crm_crm_distributor_promotion_relation", "id", CrmDistributorPromotionRelation.class);
		arp.addMapping("72crm_crm_group_member", "id", CrmGroupMember.class);
		arp.addMapping("72crm_crm_receivables_abnormal_funds", "id", CrmReceivablesAbnormalFunds.class);
	}
}

