package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminMenu<M extends BaseAdminMenu<M>> extends CrmModel<M> implements IBean {

	public M setMenuId(Long menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Long getMenuId() {
		return getLong("menu_id");
	}

	public M setParentId(Long parentId) {
		set("parent_id", parentId);
		return (M)this;
	}

	public Long getParentId() {
		return getLong("parent_id");
	}

	public M setMenuName(String menuName) {
		set("menu_name", menuName);
		return (M)this;
	}

	public String getMenuName() {
		return getStr("menu_name");
	}

	public M setRealm(String realm) {
		set("realm", realm);
		return (M)this;
	}

	public String getRealm() {
		return getStr("realm");
	}

	public M setMenuType(Integer menuType) {
		set("menu_type", menuType);
		return (M)this;
	}

	public Integer getMenuType() {
		return getInt("menu_type");
	}

	public M setSort(Long sort) {
		set("sort", sort);
		return (M)this;
	}

	public Long getSort() {
		return getLong("sort");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setRemarks(String remarks) {
		set("remarks", remarks);
		return (M)this;
	}

	public String getRemarks() {
		return getStr("remarks");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
