package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminDept<M extends BaseAdminDept<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setDeptId(Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}

	public Long getDeptId() {
		return getLong("dept_id");
	}

	public M setPid(Integer pid) {
		set("pid", pid);
		return (M)this;
	}

	public Integer getPid() {
		return getInt("pid");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setNum(Integer num) {
		set("num", num);
		return (M)this;
	}

	public Integer getNum() {
		return getInt("num");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setLeaderId(String leaderId) {
		set("leader_id", leaderId);
		return (M)this;
	}

	public String getLeaderId() {
		return getStr("leader_id");
	}

	public M setEmailGroup(String emailGroup) {
		set("email_group", emailGroup);
		return (M)this;
	}

	public String getEmailGroup() {
		return getStr("email_group");
	}

	public M setDeptLevel(Integer deptLevel) {
		set("dept_level", deptLevel);
		return (M)this;
	}

	public Integer getDeptLevel() {
		return getInt("dept_level");
	}

	public M setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public Integer getIsDelete() {
		return getInt("is_delete");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
