package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminRoleMenu<M extends BaseAdminRoleMenu<M>> extends CrmModel<M> implements IBean {

	public M setId(Long id) {
		set("id", id);
		return (M)this;
	}

	public Long getId() {
		return getLong("id");
	}

	public M setRoleId(Integer roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Integer getRoleId() {
		return getInt("role_id");
	}

	public M setMenuId(Integer menuId) {
		set("menu_id", menuId);
		return (M)this;
	}

	public Integer getMenuId() {
		return getInt("menu_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
