package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminDataDic<M extends BaseAdminDataDic<M>> extends CrmModel<M> implements IBean {

	public M setDicId(Long dicId) {
		set("dic_id", dicId);
		return (M)this;
	}

	public Long getDicId() {
		return getLong("dic_id");
	}

	public M setDicName(String dicName) {
		set("dic_name", dicName);
		return (M)this;
	}

	public String getDicName() {
		return getStr("dic_name");
	}

	public M setDicValue(String dicValue) {
		set("dic_value", dicValue);
		return (M)this;
	}

	public String getDicValue() {
		return getStr("dic_value");
	}

	public M setDicType(String dicType) {
		set("dic_type", dicType);
		return (M)this;
	}

	public String getDicType() {
		return getStr("dic_type");
	}

	public M setCreateUser(Long createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public Long getCreateUser() {
		return getLong("create_user");
	}

	public M setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public Integer getOrderNum() {
		return getInt("order_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public Long getIsDelete() {
		return getLong("is_delete");
	}

	public M setIsDelete(Integer isDelete) {
		set("is_delete", isDelete);
		return (M)this;
	}

	public M setTagName(String tagName) {
		set("tag_name", tagName);
		return (M)this;
	}

	public String getTagName() {
		return getStr("tag_name");
	}
}
