package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmAchievement<M extends BaseCrmAchievement<M>> extends CrmModel<M> implements IBean {

	public M setAchievementId(Long achievementId) {
		set("achievement_id", achievementId);
		return (M)this;
	}

	public Long getAchievementId() {
		return getLong("achievement_id");
	}

	public M setObjId(Integer objId) {
		set("obj_id", objId);
		return (M)this;
	}

	public Integer getObjId() {
		return getInt("obj_id");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setYear(String year) {
		set("year", year);
		return (M)this;
	}

	public String getYear() {
		return getStr("year");
	}

	public M setJanuary(java.math.BigDecimal january) {
		set("january", january);
		return (M)this;
	}

	public java.math.BigDecimal getJanuary() {
		return get("january");
	}

	public M setFebruary(java.math.BigDecimal february) {
		set("february", february);
		return (M)this;
	}

	public java.math.BigDecimal getFebruary() {
		return get("february");
	}

	public M setMarch(java.math.BigDecimal march) {
		set("march", march);
		return (M)this;
	}

	public java.math.BigDecimal getMarch() {
		return get("march");
	}

	public M setApril(java.math.BigDecimal april) {
		set("april", april);
		return (M)this;
	}

	public java.math.BigDecimal getApril() {
		return get("april");
	}

	public M setMay(java.math.BigDecimal may) {
		set("may", may);
		return (M)this;
	}

	public java.math.BigDecimal getMay() {
		return get("may");
	}

	public M setJune(java.math.BigDecimal june) {
		set("june", june);
		return (M)this;
	}

	public java.math.BigDecimal getJune() {
		return get("june");
	}

	public M setJuly(java.math.BigDecimal july) {
		set("july", july);
		return (M)this;
	}

	public java.math.BigDecimal getJuly() {
		return get("july");
	}

	public M setAugust(java.math.BigDecimal august) {
		set("august", august);
		return (M)this;
	}

	public java.math.BigDecimal getAugust() {
		return get("august");
	}

	public M setSeptember(java.math.BigDecimal september) {
		set("september", september);
		return (M)this;
	}

	public java.math.BigDecimal getSeptember() {
		return get("september");
	}

	public M setOctober(java.math.BigDecimal october) {
		set("october", october);
		return (M)this;
	}

	public java.math.BigDecimal getOctober() {
		return get("october");
	}

	public M setNovember(java.math.BigDecimal november) {
		set("november", november);
		return (M)this;
	}

	public java.math.BigDecimal getNovember() {
		return get("november");
	}

	public M setDecember(java.math.BigDecimal december) {
		set("december", december);
		return (M)this;
	}

	public java.math.BigDecimal getDecember() {
		return get("december");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setYeartarget(java.math.BigDecimal yeartarget) {
		set("yeartarget", yeartarget);
		return (M)this;
	}

	public java.math.BigDecimal getYeartarget() {
		return get("yeartarget");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
