package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 *
 * @author liming.guo
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmBusinessStatusVerification<M extends BaseCrmBusinessStatusVerification<M>> extends CrmModel<M> implements IBean {

    public M setId(Long id) {
        set("id", id);
        return (M) this;
    }

    public Long getId() {
        return getLong("id");
    }

    public M setName(String name) {
        set("name", name);
        return (M) this;
    }

    public String getName() {
        return getStr("name");
    }

    public M setStatusId(Long statusId) {
        set("status_id", statusId);
        return (M) this;
    }

    public Long getStatusId() {
        return getLong("status_id");
    }

    public M setCreateUserId(Long createUserId) {
        set("create_user_id", createUserId);
        return (M) this;
    }

    public Long getCreateUserId() {
        return getLong("create_user_id");
    }

    public M setIsDeleted(Integer isDeleted) {
        set("is_deleted", isDeleted);
        return (M) this;
    }

    public Integer getIsDeleted() {
        return getInt("is_deleted");
    }

    public M setGmtCreate(java.util.Date gmtCreate) {
        set("gmt_create", gmtCreate);
        return (M) this;
    }

    public java.util.Date getGmtCreate() {
        return get("gmt_create");
    }

    public M setGmtModified(java.util.Date gmtModified) {
        set("gmt_modified", gmtModified);
        return (M) this;
    }

    public java.util.Date getGmtModified() {
        return get("gmt_modified");
    }

    public M setEnvFlag(String envFlag) {
        set("env_flag", envFlag);
        return (M) this;
    }

    public String getEnvFlag() {
        return getStr("env_flag");
    }

    public M setRemark(String remark) {
        set("remark", remark);
        return (M) this;
    }

    public String getRemark() {
        return getStr("remark");
    }

}
