package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminSceneDefault<M extends BaseAdminSceneDefault<M>> extends CrmModel<M> implements IBean {

	public M setDefaultId(Long defaultId) {
		set("default_id", defaultId);
		return (M)this;
	}

	public Long getDefaultId() {
		return getLong("default_id");
	}

	public M setType(Integer type) {
		set("type", type);
		return (M)this;
	}

	public Integer getType() {
		return getInt("type");
	}

	public M setUserId(Long userId) {
		set("user_id", userId);
		return (M)this;
	}

	public Long getUserId() {
		return getLong("user_id");
	}

	public M setSceneId(Integer sceneId) {
		set("scene_id", sceneId);
		return (M)this;
	}

	public Integer getSceneId() {
		return getInt("scene_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
