package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminRole<M extends BaseAdminRole<M>> extends CrmModel<M> implements IBean {

	public M setRoleId(Long roleId) {
		set("role_id", roleId);
		return (M)this;
	}

	public Long getRoleId() {
		return getLong("role_id");
	}

	public M setRoleName(String roleName) {
		set("role_name", roleName);
		return (M)this;
	}

	public String getRoleName() {
		return getStr("role_name");
	}

	public M setRoleType(Integer roleType) {
		set("role_type", roleType);
		return (M)this;
	}

	public Integer getRoleType() {
		return getInt("role_type");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}

	public String getRemark() {
		return getStr("remark");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setDataType(Integer dataType) {
		set("data_type", dataType);
		return (M)this;
	}

	public Integer getDataType() {
		return getInt("data_type");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
