package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminScenario<M extends BaseAdminScenario<M>> extends CrmModel<M> implements IBean {

	public M setScenarioId(Long scenarioId) {
		set("scenario_id", scenarioId);
		return (M)this;
	}

	public Long getScenarioId() {
		return getLong("scenario_id");
	}

	public M setDeptId(Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}

	public Long getDeptId() {
		return getLong("dept_id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setOrderNum(Integer orderNum) {
		set("order_num", orderNum);
		return (M)this;
	}

	public Integer getOrderNum() {
		return getInt("order_num");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
