package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminUserCapacity<M extends BaseAdminUserCapacity<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setUserId(Long userId) {
		set("user_id", userId);
		return (M)this;
	}
	
	public Long getUserId() {
		return getLong("user_id");
	}

	public M setUserName(String userName) {
		set("user_name", userName);
		return (M)this;
	}
	
	public String getUserName() {
		return getStr("user_name");
	}

	public M setInspectCap(Integer inspectCap) {
		set("inspect_cap", inspectCap);
		return (M)this;
	}
	
	public Integer getInspectCap() {
		return getInt("inspect_cap");
	}

	public M setRelateCap(Integer relateCap) {
		set("relate_cap", relateCap);
		return (M)this;
	}
	
	public Integer getRelateCap() {
		return getInt("relate_cap");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
