package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseCrmBusinessType<M extends BaseCrmBusinessType<M>> extends CrmModel<M> implements IBean {

	public M setTypeId(Long typeId) {
		set("type_id", typeId);
		return (M)this;
	}

	public Long getTypeId() {
		return getLong("type_id");
	}

	public M setName(String name) {
		set("name", name);
		return (M)this;
	}

	public String getName() {
		return getStr("name");
	}

	public M setDeptIds(String deptIds) {
		set("dept_ids", deptIds);
		return (M)this;
	}

	public String getDeptIds() {
		return getStr("dept_ids");
	}

	public M setCreateUserId(Integer createUserId) {
		set("create_user_id", createUserId);
		return (M)this;
	}

	public Integer getCreateUserId() {
		return getInt("create_user_id");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

	public M setStatus(Integer status) {
		set("status", status);
		return (M)this;
	}

	public Integer getStatus() {
		return getInt("status");
	}

	public M setDeptEmailGroup(String deptEmailGroup) {
		set("dept_email_group", deptEmailGroup);
		return (M)this;
	}

	public String getDeptEmailGroup() {
		return getStr("dept_email_group");
	}

}
