package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminLookUpLog<M extends BaseAdminLookUpLog<M>> extends CrmModel<M> implements IBean {

	public M setLogId(Long logId) {
		set("log_id", logId);
		return (M)this;
	}

	public Long getLogId() {
		return getLong("log_id");
	}

	public M setCreateUser(Long createUser) {
		set("create_user", createUser);
		return (M)this;
	}

	public Long getCreateUser() {
		return getLong("create_user");
	}

	public M setBillsId(String billsId) {
		set("bills_id", billsId);
		return (M)this;
	}

	public String getBillsId() {
		return getStr("bills_id");
	}

	public M setLookUpName(String lookUpName) {
		set("look_up_name", lookUpName);
		return (M)this;
	}

	public String getLookUpName() {
		return getStr("look_up_name");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}
	
	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}
	
	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
