package com.kakarote.crm9.erp.admin.entity.base;

import com.jfinal.plugin.activerecord.CrmModel;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseAdminDeptCapacity<M extends BaseAdminDeptCapacity<M>> extends CrmModel<M> implements IBean {

	public M setId(java.math.BigInteger id) {
		set("id", id);
		return (M)this;
	}
	
	public java.math.BigInteger getId() {
		return get("id");
	}

	public M setBizDeptId(Long bizDeptId) {
		set("biz_dept_id", bizDeptId);
		return (M)this;
	}
	
	public Long getBizDeptId() {
		return getLong("biz_dept_id");
	}

	public M setDeptId(Long deptId) {
		set("dept_id", deptId);
		return (M)this;
	}
	
	public Long getDeptId() {
		return getLong("dept_id");
	}

	public M setDeptName(String deptName) {
		set("dept_name", deptName);
		return (M)this;
	}
	
	public String getDeptName() {
		return getStr("dept_name");
	}

	public M setCapacity(Integer capacity) {
		set("capacity", capacity);
		return (M)this;
	}
	
	public Integer getCapacity() {
		return getInt("capacity");
	}

	public M setInspectFlag(Integer inspectFlag) {
		set("inspect_flag", inspectFlag);
		return (M)this;
	}
	
	public Integer getInspectFlag() {
		return getInt("inspect_flag");
	}

	public M setInspectDays(Integer inspectDays) {
		set("inspect_days", inspectDays);
		return (M)this;
	}
	
	public Integer getInspectDays() {
		return getInt("inspect_days");
	}

	public M setRelateOutFlag(Integer relateOutFlag) {
		set("relate_out_flag", relateOutFlag);
		return (M)this;
	}
	
	public Integer getRelateOutFlag() {
		return getInt("relate_out_flag");
	}

	public M setRelateOutDays(Integer relateOutDays) {
		set("relate_out_days", relateOutDays);
		return (M)this;
	}
	
	public Integer getRelateOutDays() {
		return getInt("relate_out_days");
	}

	public M setRelateLockFlag(Integer relateLockFlag) {
		set("relate_lock_flag", relateLockFlag);
		return (M)this;
	}
	
	public Integer getRelateLockFlag() {
		return getInt("relate_lock_flag");
	}

	public M setRelateLockDays(Integer relateLockDays) {
		set("relate_lock_days", relateLockDays);
		return (M)this;
	}
	
	public Integer getRelateLockDays() {
		return getInt("relate_lock_days");
	}

	public M setGmtCreate(java.util.Date gmtCreate) {
		set("gmt_create", gmtCreate);
		return (M)this;
	}
	
	public java.util.Date getGmtCreate() {
		return get("gmt_create");
	}

	public M setGmtModified(java.util.Date gmtModified) {
		set("gmt_modified", gmtModified);
		return (M)this;
	}
	
	public java.util.Date getGmtModified() {
		return get("gmt_modified");
	}

	public M setIsDeleted(Integer isDeleted) {
		set("is_deleted", isDeleted);
		return (M)this;
	}
	
	public Integer getIsDeleted() {
		return getInt("is_deleted");
	}

	public M setEnvFlag(String envFlag) {
		set("env_flag", envFlag);
		return (M)this;
	}
	
	public String getEnvFlag() {
		return getStr("env_flag");
	}

	public M setRemark(String remark) {
		set("remark", remark);
		return (M)this;
	}
	
	public String getRemark() {
		return getStr("remark");
	}

}
